#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "efex-common.h"
#if defined(_WIN32)
#include <windows.h>
#define sleep(x) Sleep(x * 1000)
#else
#include <unistd.h>
#endif

#include "libefex.h"

#define DEFAULT_BUFFER_SIZE 4096
#define DEFAULT_ADDRESS 0x40000000
#define WORK_MODE_USB_PRODUCT 0x10

struct boot_file_head_t {
	uint32_t jump_instruction; /* one intruction jumping to real code */
	uint8_t magic[8];          /* ="eGON.BT0" */
	uint32_t check_sum;        /* generated by PC */
	uint32_t length;           /* generated by LD */
	uint32_t pub_head_size;    /* the size of boot_file_head_t */
	uint8_t pub_head_vsn[4];   /* the version of boot_file_head_t */
	uint32_t ret_addr;         /* the run addr */
	uint32_t run_addr;         /* the return addr */
	uint32_t boot_cpu;         /* eGON version */
	uint8_t platform[8];       /* platform information */
};

struct dram_param_info_t {
	uint32_t dram_init_flag;
	uint32_t dram_update_flag;
	uint32_t dram_para[32];
};

struct uboot_base_head_t {
	uint32_t jump_instruction; /* one intruction jumping to real code */
	uint8_t magic[8];          /* ="u-boot" */
	uint32_t check_sum;        /* generated by PC */
	uint32_t align_size;       /* align size in byte */
	uint32_t length;           /* the size of all file */
	uint32_t uboot_length;     /* the size of uboot */
	uint8_t version[8];        /* uboot version */
	uint8_t platform[8];       /* platform information */
	uint32_t run_addr;
};

struct uboot_normal_gpio_cfg_t {
	uint8_t port;      /* port : PA/PB/PC ... */
	uint8_t port_num;  /* internal port num: PA00/PA01 ... */
	uint8_t mul_sel;   /* function num: input/output/io-disalbe ...*/
	uint8_t pull;      /* pull-up/pull-down/no-pull */
	uint8_t drv_level; /* driver level: level0-3*/
	uint8_t data;      /* pin state when the port is configured as input or output*/
	uint8_t reserved[2];
};

struct uboot_data_head_t {
	uint32_t dram_para[32];
	int run_clock;                                  /* Mhz */
	int run_core_vol;                               /* mV */
	int uart_port;                                  /* UART ctrl num */
	struct uboot_normal_gpio_cfg_t uart_gpio[2];    /* UART GPIO info */
	int twi_port;                                   /* TWI ctrl num */
	struct uboot_normal_gpio_cfg_t twi_gpio[2];     /* TWI GPIO info */
	int work_mode;                                  /* boot,usb-burn, card-burn */
	int storage_type;                               /* 0:nand 1:sdcard 2:spinor */
	struct uboot_normal_gpio_cfg_t nand_gpio[32];   /* nand GPIO info */
	uint8_t nand_spare_data[256];                   /* nand info */
	struct uboot_normal_gpio_cfg_t sdcard_gpio[32]; /* sdcard GPIO info */
	uint8_t sdcard_spare_data[256];                 /* sdcard info */
	uint8_t secureos_exist;
	uint8_t monitor_exist;
	uint8_t func_mask;                  /* see enum UBOOT_FUNC_MASK_EN */
	uint8_t uboot_backup;               /* use in OTA update */
	uint32_t uboot_start_sector_in_mmc; /*use in OTA update */
	int dtb_offset;                     /*device tree in uboot */
	int boot_package_size;              /*boot package size, boot0 pass this value */
	uint32_t dram_scan_size;            /*dram real size */
	int reserved[1];                    /*reseved,256bytes align */
	/*expend boot_ext[0](int[4]) in uboot 2014*/
	uint16_t pmu_type;
	uint16_t uart_input;
	uint16_t key_input;
	uint8_t secure_mode; /*update by update_uboot*/
	uint8_t debug_mode;  /*update by update_uboot*/
	int reserved2[2];
};

struct uboot_ext_head_t {
	int data[4];
};

struct uboot_head_t {
	struct uboot_base_head_t uboot_head;
	struct uboot_data_head_t uboot_data;
	struct uboot_ext_head_t uboot_ext[15];
	uint8_t hash[64];
};

static void usage(const char *prog_name) {
	printf("Usage: %s [-f file_to_download] [-u file_to_upload]\n", prog_name);
	printf("Options:\n");
	printf("  -f file   Download data from specified file to device\n");
	printf("  -u file   Upload data from device to specified file\n");
	printf("  No args   Run default test sequence\n");
}

int init_device_fes(struct sunxi_efex_ctx_t *ctx, const char *fex_file, const char *uboot_file) {
	int ret = 0;

	// Process FEX file
	if (fex_file) {
		FILE *fp = fopen(fex_file, "rb");
		if (!fp) {
			fprintf(stderr, "ERROR: %s: %s\r\n", sunxi_efex_strerror(EFEX_ERR_FILE_OPEN), fex_file);
			return EFEX_ERR_FILE_OPEN;
		}

		// Get file size
		fseek(fp, 0, SEEK_END);
		const long file_size = ftell(fp);
		fseek(fp, 0, SEEK_SET);

		if (file_size <= 0) {
			fprintf(stderr, "ERROR: %s: %s\r\n", sunxi_efex_strerror(EFEX_ERR_FILE_SIZE), fex_file);
			fclose(fp);
			return EFEX_ERR_FILE_SIZE;
		}

		// Allocate buffer for file content
		char *buffer = malloc(file_size);
		if (!buffer) {
			fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(EFEX_ERR_MEMORY));
			fclose(fp);
			return EFEX_ERR_MEMORY;
		}

		// Read file content
		const size_t bytes_read = fread(buffer, 1, file_size, fp);
		fclose(fp);

		if (bytes_read != (size_t) file_size) {
			fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(EFEX_ERR_FILE_READ));
			free(buffer);
			return EFEX_ERR_FILE_READ;
		}

		const struct boot_file_head_t *fex_head = (const struct boot_file_head_t *) buffer;

		struct dram_param_info_t dram_param_info = {
				.dram_init_flag = 0,
				.dram_update_flag = 0,
		};

		printf("Clear DRAM param area at 0x%08x\n", fex_head->ret_addr);
		ret = sunxi_efex_fel_write(ctx, fex_head->ret_addr, (const char *) &dram_param_info,
		                           sizeof(struct dram_param_info_t));
		if (ret != EFEX_ERR_SUCCESS) {
			fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(ret));
			free(buffer);
			return ret;
		}

		printf("Downloading %ld bytes from %s to device...\n", file_size, fex_file);
		ret = sunxi_efex_fel_write(ctx, fex_head->run_addr, buffer, (ssize_t) file_size);
		if (ret != EFEX_ERR_SUCCESS) {
			fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(ret));
			free(buffer);
			return ret;
		}
		ret = sunxi_efex_fel_exec(ctx, fex_head->run_addr);
		if (ret != EFEX_ERR_SUCCESS) {
			fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(ret));
			free(buffer);
			return ret;
		}

		sleep(1);

		ret = sunxi_efex_fel_read(ctx, fex_head->ret_addr, (char *) &dram_param_info, sizeof(struct dram_param_info_t));
		if (ret != EFEX_ERR_SUCCESS) {
			fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(ret));
			free(buffer);
			return ret;
		}

		printf("DRAM init flag: %u\n", dram_param_info.dram_init_flag);
		printf("DRAM update flag: %u\n", dram_param_info.dram_update_flag);
		for (size_t i = 0; i < 32; i++) {
			printf("DRAM param[%zu]: 0x%08x\n", i, dram_param_info.dram_para[i]);
		}

		if (dram_param_info.dram_init_flag == 1) {
			free(buffer);
			printf("DRAM init failed\n");
			return -1;
		}
		free(buffer);
		printf("FEX file download completed successfully\n");
	}

	// Process U-Boot file
	if (uboot_file) {
		FILE *fp = fopen(uboot_file, "rb");
		if (!fp) {
			fprintf(stderr, "ERROR: %s: %s\r\n", sunxi_efex_strerror(EFEX_ERR_FILE_OPEN), uboot_file);
			return EFEX_ERR_FILE_OPEN;
		}

		// Get file size
		fseek(fp, 0, SEEK_END);
		const long file_size = ftell(fp);
		fseek(fp, 0, SEEK_SET);

		if (file_size <= 0) {
			fprintf(stderr, "ERROR: %s: %s\r\n", sunxi_efex_strerror(EFEX_ERR_FILE_SIZE), uboot_file);
			fclose(fp);
			return EFEX_ERR_FILE_SIZE;
		}

		// Allocate buffer for file content
		char *buffer = malloc(file_size);
		if (!buffer) {
			fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(EFEX_ERR_MEMORY));
			fclose(fp);
			return EFEX_ERR_MEMORY;
		}

		// Read file content
		const size_t bytes_read = fread(buffer, 1, file_size, fp);
		fclose(fp);

		if (bytes_read != (size_t) file_size) {
			fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(EFEX_ERR_FILE_READ));
			free(buffer);
			return EFEX_ERR_FILE_READ;
		}

		struct uboot_head_t *uboot_head = (struct uboot_head_t *) buffer;
		uboot_head->uboot_data.work_mode = WORK_MODE_USB_PRODUCT;

		printf("Downloading %ld bytes from %s to device...\n", file_size, uboot_file);

		ret = sunxi_efex_fel_write(ctx, uboot_head->uboot_head.run_addr, buffer, (ssize_t) file_size);
		if (ret != EFEX_ERR_SUCCESS) {
			fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(ret));
			free(buffer);
			sunxi_usb_exit(ctx);
			return ret;
		}
		ret = sunxi_efex_fel_exec(ctx, uboot_head->uboot_head.run_addr);
		if (ret != EFEX_ERR_SUCCESS) {
			fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(ret));
			free(buffer);
			sunxi_usb_exit(ctx);
			return ret;
		}
		free(buffer);

		printf("U-Boot file download completed successfully\n");
	}

	sunxi_usb_exit(ctx);

	sleep(5);

	while (1) {
		ret = sunxi_scan_usb_device(ctx);
		if (ret == EFEX_ERR_SUCCESS) {
			break;
		}
		sleep(1);
	}

	while (1) {
		printf("Device reconnected, try init in fes mode\n");
		ret = sunxi_usb_init(ctx);
		if (ret != EFEX_ERR_SUCCESS) {
			printf("USB init failed: %s\n", sunxi_efex_strerror(ret));
			sleep(3);
			sunxi_usb_exit(ctx);
			sunxi_scan_usb_device(ctx);
			continue;
		}

		ret = sunxi_efex_init(ctx);
		if (ret != EFEX_ERR_SUCCESS) {
			printf("EFEX init failed: %s\n", sunxi_efex_strerror(ret));
			sleep(3);
			sunxi_usb_exit(ctx);
			sunxi_scan_usb_device(ctx);
			continue;
		}

		if (ctx->resp.mode == DEVICE_MODE_SRV) {
			break;
		}

		sleep(3);
		sunxi_usb_exit(ctx);
		sunxi_scan_usb_device(ctx);
	}

	printf("Device reconnected and in FES mode!\n");

	return 0;
}

int main(const int argc, char *argv[]) {
	struct sunxi_efex_ctx_t ctx = {0};
	int ret = 0;
	const char *fex_file = NULL;
	const char *uboot_file = NULL;

	// Parse command line arguments
	for (int arg_index = 1; arg_index < argc; arg_index++) {
		if (strcmp(argv[arg_index], "-h") == 0 || strcmp(argv[arg_index], "--help") == 0) {
			usage(argv[0]);
			return 0;
		}
		if (strcmp(argv[arg_index], "-f") == 0) {
			if (arg_index + 1 < argc) {
				fex_file = argv[++arg_index];
			} else {
				fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(EFEX_ERR_INVALID_PARAM));
				usage(argv[0]);
				return EFEX_ERR_INVALID_PARAM;
			}
		} else if (strcmp(argv[arg_index], "-u") == 0) {
			if (arg_index + 1 < argc) {
				uboot_file = argv[++arg_index];
			} else {
				fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(EFEX_ERR_INVALID_PARAM));
				usage(argv[0]);
				return EFEX_ERR_INVALID_PARAM;
			}
		} else {
			fprintf(stderr, "ERROR: %s\n", sunxi_efex_strerror(EFEX_ERR_INVALID_PARAM));
			usage(argv[0]);
			return EFEX_ERR_INVALID_PARAM;
		}
	}

	ret = sunxi_scan_usb_device(&ctx);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		return ret;
	}
	ret = sunxi_usb_init(&ctx);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	ret = sunxi_efex_init(&ctx);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}

	printf("Found EFEX device\n");
	printf("Magic: %s\n", ctx.resp.magic);
	printf("ID: 0x%08x\n", ctx.resp.id);
	printf("Firmware: 0x%08x\n", ctx.resp.firmware);
	printf("Mode: 0x%04x\n", ctx.resp.mode);
	printf("Data Flag: 0x%02x\n", ctx.resp.data_flag);
	printf("Data Length: 0x%02x\n", ctx.resp.data_length);
	printf("Data Start Address: 0x%08x\n", ctx.resp.data_start_address);

	printf("Reserved: ");
	for (int i = 0; i < sizeof(ctx.resp.reserved); i++) {
		printf("%02x ", (uint8_t) ctx.resp.reserved[i]);
	}
	printf("\n");

	if (ctx.resp.mode == DEVICE_MODE_FEL) {
		init_device_fes(&ctx, fex_file, uboot_file);
	}

	uint32_t flash_type = 0;
	ret = sunxi_efex_fes_query_storage(&ctx, &flash_type);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Storage Type: 0x%08x\n", flash_type);

	ret = sunxi_efex_fes_flash_set_onoff(&ctx, &flash_type, 0);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Flash Set Off\n");

	uint32_t flash_size = 0;
	ret = sunxi_efex_fes_probe_flash_size(&ctx, &flash_size);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Flash Size: 0x%08x\n", flash_size);

	ret = sunxi_efex_fes_flash_set_onoff(&ctx, &flash_type, 1);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Flash Set On\n");

	ret = sunxi_efex_fes_probe_flash_size(&ctx, &flash_size);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Flash Size: 0x%08x\n", flash_size);

	char down_buf[16] = "Hello, EFEX FES\0";
	ret = sunxi_efex_fes_down(&ctx, down_buf, 16, 0x40000000, SUNXI_EFEX_DRAM_TAG);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Download data: %s\n", down_buf);

	char up_buf[16] = {0};
	ret = sunxi_efex_fes_up(&ctx, up_buf, 16, 0x40000000, SUNXI_EFEX_DRAM_TAG);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Upload Data: %s\n", up_buf);

	// maybe not supported
#if 0
	const uint8_t chip_id[129] = {0};
	ret = sunxi_efex_fes_get_chipid(&ctx, chip_id);
	if (ret != EFEX_ERR_SUCCESS) {
		fprintf(stderr, "ERROR: %s\r\n", sunxi_efex_strerror(ret));
		sunxi_usb_exit(&ctx);
		return ret;
	}
	printf("Chip ID: %s\n", chip_id);
#endif
}
