import type { ChipInfo } from '../Drivers/Types';

export const aw1886: ChipInfo = {
    id: '1886',
    chipMark: {
        "V853": 0x7800,
        "V851s": 0x210C,
        "V553": 0x7E00,
        "V853s": 0x7C00
    },
    pinctrl: {
        pio: {
            reg_base: 0x2000000,
            version: 2,
            pin_bank_num: {
                PA: 22,
                PC: 12,
                PD: 23,
                PE: 18,
                PF: 7,
                PG: 8,
                PH: 16,
                PI: 5
            },
            pin_mux: {
                PA0: ["gpio_in", "gpio_out", "mipia_rx", "ncsi", "null", "test", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA1: ["gpio_in", "gpio_out", "mipia_rx", "ncsi", "null", "test", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA10: ["gpio_in", "gpio_out", "mipib_rx", "ncsi", "mipi_csi_mclk0", "twi0", "clk", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA11: ["gpio_in", "gpio_out", "mipib_rx", "ncsi", "mipi_csi_mclk1", "twi0", "clk", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA12: ["gpio_in", "gpio_out", "null", "ncsi", "mipi_csi_mclk0", "uart0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA13: ["gpio_in", "gpio_out", "null", "ncsi", "mipi_csi_mclk1", "uart0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA14: ["gpio_in", "gpio_out", "null", "ncsi", "twi1", "clk", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA15: ["gpio_in", "gpio_out", "null", "ncsi", "twi1", "clk", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA16: ["gpio_in", "gpio_out", "null", "ncsi", "twi0", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA17: ["gpio_in", "gpio_out", "null", "ncsi", "twi0", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA18: ["gpio_in", "gpio_out", "null", "ncsi", "wiegand", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA19: ["gpio_in", "gpio_out", "null", "ncsi", "wiegand", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA2: ["gpio_in", "gpio_out", "mipia_rx", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA20: ["gpio_in", "gpio_out", "null", "ncsi_mclk", "csi", "tcon", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA21: ["gpio_in", "gpio_out", "null", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA3: ["gpio_in", "gpio_out", "mipia_rx", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA4: ["gpio_in", "gpio_out", "mipia_rx", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA5: ["gpio_in", "gpio_out", "mipia_rx", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA6: ["gpio_in", "gpio_out", "mipib_rx", "ncsi", "twi1", "pwm0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA7: ["gpio_in", "gpio_out", "mipib_rx", "ncsi", "twi1", "pwm1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA8: ["gpio_in", "gpio_out", "mipib_rx", "twi4", "twi3", "pwm2", "uart2", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA9: ["gpio_in", "gpio_out", "mipib_rx", "twi4", "twi3", "pwm3", "uart2", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC0: ["gpio_in", "gpio_out", "spif", "sdc2", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC1: ["gpio_in", "gpio_out", "spif", "sdc2", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC10: ["gpio_in", "gpio_out", "spif", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC11: ["gpio_in", "gpio_out", "null", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC2: ["gpio_in", "gpio_out", "spif", "sdc2", "spi0", "boot_sel0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC3: ["gpio_in", "gpio_out", "spif", "sdc2", "spi0", "boot_sel1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC4: ["gpio_in", "gpio_out", "spif", "sdc2", "spi0", "pwm4", "twi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC5: ["gpio_in", "gpio_out", "spif", "sdc2", "spi0", "pwm4", "twi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC6: ["gpio_in", "gpio_out", "spif", "sdc2", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC7: ["gpio_in", "gpio_out", "spif", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC8: ["gpio_in", "gpio_out", "spif", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC9: ["gpio_in", "gpio_out", "spif", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD0: ["gpio_in", "gpio_out", "lcd", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD1: ["gpio_in", "gpio_out", "lcd", "pwm0", "rmii", "dsi", "spi1", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD10: ["gpio_in", "gpio_out", "lcd", "i2s1", "null", "dsi", "null", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD11: ["gpio_in", "gpio_out", "lcd", "i2s1", "null", "dsi", "null", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD12: ["gpio_in", "gpio_out", "lcd", "i2s1", "null", "dmic", "null", "pwm11", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD13: ["gpio_in", "gpio_out", "lcd", "i2s1", "null", "dmic", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD14: ["gpio_in", "gpio_out", "lcd", "i2s1", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD15: ["gpio_in", "gpio_out", "lcd", "i2s1", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD16: ["gpio_in", "gpio_out", "lcd", "i2s1", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD17: ["gpio_in", "gpio_out", "lcd", "i2s1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD18: ["gpio_in", "gpio_out", "lcd", "null", "rmii", "spi2", "twi3", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD19: ["gpio_in", "gpio_out", "lcd", "pwm9", "tcon", "spi2", "twi3", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD2: ["gpio_in", "gpio_out", "lcd", "pwm1", "rmii", "dsi", "spi1", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD20: ["gpio_in", "gpio_out", "lcd", "pwm10", "rmii", "spi2", "twi2", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD21: ["gpio_in", "gpio_out", "lcd", "null", "rmii", "spi2", "twi2", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD22: ["gpio_in", "gpio_out", "pwm9", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD3: ["gpio_in", "gpio_out", "lcd", "pwm2", "rmii", "dsi", "spi1", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD4: ["gpio_in", "gpio_out", "lcd", "pwm3", "rmii", "dsi", "spi1", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD5: ["gpio_in", "gpio_out", "lcd", "pwm4", "rmii", "dsi", "spi1", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD6: ["gpio_in", "gpio_out", "lcd", "pwm5", "rmii", "dsi", "spi1", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD7: ["gpio_in", "gpio_out", "lcd", "pwm6", "rmii", "dsi", "spi1", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD8: ["gpio_in", "gpio_out", "lcd", "pwm7", "rmii", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD9: ["gpio_in", "gpio_out", "lcd", "pwm8", "null", "dsi", "null", "rmii", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE0: ["gpio_in", "gpio_out", "ncsi", "rgmii", "i2s1", "pwm0", "sdc1", "uart3", "twi3", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE1: ["gpio_in", "gpio_out", "ncsi_mclk", "rgmii", "i2s1", "pwm1", "sdc1", "uart3", "twi3", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE10: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "pwm10", "uart2", "i2s1", "wiegand", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE11: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "csi", "uart2", "i2s1", "wiegand", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE12: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "mipi_csi_mclk0", "uart2", "uart3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE13: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "mipi_csi_mclk1", "uart2", "uart3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE14: ["gpio_in", "gpio_out", "ncsi", "rgmii", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE15: ["gpio_in", "gpio_out", "ncsi", "rgmii", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE16: ["gpio_in", "gpio_out", "twi0", "twi4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE17: ["gpio_in", "gpio_out", "twi0", "twi4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE2: ["gpio_in", "gpio_out", "ncsi", "rgmii", "i2s1", "pwm2", "sdc1", "uart3", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE3: ["gpio_in", "gpio_out", "ncsi", "rgmii", "i2s1", "pwm3", "sdc1", "uart3", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE4: ["gpio_in", "gpio_out", "ncsi", "rgmii", "i2s1", "pwm4", "sdc1", "uart3", "twi0", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE5: ["gpio_in", "gpio_out", "ncsi", "rgmii", "null", "pwm5", "sdc1", "uart3", "twi0", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE6: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "pwm6", "uart1", "null", "twi4", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE7: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "pwm7", "uart1", "i2s1", "twi4", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE8: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "pwm8", "wiegand", "i2s1", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE9: ["gpio_in", "gpio_out", "ncsi", "rgmii", "lcd", "pwm9", "wiegand", "i2s1", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF0: ["gpio_in", "gpio_out", "sdc0", "jtag", "spi0", "spi2", "r_jtag", "cpu", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF1: ["gpio_in", "gpio_out", "sdc0", "jtag", "spi0", "spi2", "r_jtag", "cpu", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF2: ["gpio_in", "gpio_out", "sdc0", "uart0", "spi0", "spi2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF3: ["gpio_in", "gpio_out", "sdc0", "jtag", "spi0", "spi2", "r_jtag", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF4: ["gpio_in", "gpio_out", "sdc0", "uart0", "spi0", "spi2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF5: ["gpio_in", "gpio_out", "sdc0", "jtag", "null", "null", "r_jtag", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF6: ["gpio_in", "gpio_out", "dbg_clk", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG0: ["gpio_in", "gpio_out", "sdc1", "lcd", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG1: ["gpio_in", "gpio_out", "sdc1", "lcd", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG2: ["gpio_in", "gpio_out", "sdc1", "lcd", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG3: ["gpio_in", "gpio_out", "sdc1", "lcd", "uart3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG4: ["gpio_in", "gpio_out", "sdc1", "lcd", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG5: ["gpio_in", "gpio_out", "sdc1", "lcd", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG6: ["gpio_in", "gpio_out", "twi4", "clk", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG7: ["gpio_in", "gpio_out", "twi4", "clk", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH0: ["gpio_in", "gpio_out", "pwm0", "i2s0", "spi1", "uart3", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH1: ["gpio_in", "gpio_out", "pwm1", "i2s0", "spi1", "uart3", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH10: ["gpio_in", "gpio_out", "pwm10", "rmii", "twi3", "uart0", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH11: ["gpio_in", "gpio_out", "jtag", "rmii", "r_jtag", "twi2", "spi3", "clk", "pwm4", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH12: ["gpio_in", "gpio_out", "jtag", "rmii", "r_jtag", "twi2", "spi3", "clk", "pwm5", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH13: ["gpio_in", "gpio_out", "jtag", "mdc", "r_jtag", "twi3", "spi3", "wiegand", "pwm6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH14: ["gpio_in", "gpio_out", "jtag", "mdio", "r_jtag", "twi3", "spi3", "wiegand", "pwm7", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH15: ["gpio_in", "gpio_out", "clk", "ephy_25m", "null", "null", "spi3", "null", "pwm8", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH2: ["gpio_in", "gpio_out", "pwm2", "i2s0", "spi1", "uart3", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH3: ["gpio_in", "gpio_out", "pwm3", "i2s0", "spi1", "uart3", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH4: ["gpio_in", "gpio_out", "pwm4", "i2s0", "spi1", "clk", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH5: ["gpio_in", "gpio_out", "pwm5", "rmii", "twi2", "uart2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH6: ["gpio_in", "gpio_out", "pwm6", "rmii", "twi2", "uart2", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH7: ["gpio_in", "gpio_out", "pwm7", "rmii", "uart0", "uart2", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH8: ["gpio_in", "gpio_out", "pwm8", "rmii", "uart0", "uart2", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH9: ["gpio_in", "gpio_out", "pwm9", "rmii", "twi3", "uart0", "i2s1", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI0: ["gpio_in", "gpio_out", "mipi_csi_mclk0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI1: ["gpio_in", "gpio_out", "csi", "null", "spi2", "twi1", "twi4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI2: ["gpio_in", "gpio_out", "csi", "tcon", "spi2", "twi1", "twi4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI3: ["gpio_in", "gpio_out", "null", "null", "spi2", "twi0", "twi3", "clk", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI4: ["gpio_in", "gpio_out", "null", "null", "spi2", "twi0", "twi3", "clk", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
    }
};