import type { ChipInfo } from '../Drivers/Types';

export const aw1882: ChipInfo = {
    id: '1882',
    chipMark: {
        "V821M2-WXX": 0x5800,
        "V821M2-XXX": 0x6800,
        "V821M2-EXX": 0x7800,
        "V821L2-XXX": 0x5C00,
        "V821L2-WXX": 0x6C00,
        "V821C2-XXX": 0x2800,
        "V521D2-WXX": 0x6E00,
        "V821": 0x0
    },
    pinctrl: {
        pio: {
            reg_base: 0x42000000,
            version: 2,
            pin_bank_num: {
                PA: 13,
                PC: 17,
                PD: 24
            },
            pin_mux: {
                PA0: ["gpio_in", "gpio_out", "csi", "pwm0_5", "null", "null", "clk", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA1: ["gpio_in", "gpio_out", "mipi", "twi1", "twi0", "uart1", "pwm0_10", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA10: ["gpio_in", "gpio_out", "mipib", "twi0", "twi1", "pwm0_3", "uart3", "spi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA11: ["gpio_in", "gpio_out", "mipib", "twi1", "twi0", "pwm0_4", "uart3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA12: ["gpio_in", "gpio_out", "mipib", "twi1", "twi0", "pwm0_5", "uart3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA2: ["gpio_in", "gpio_out", "mipi", "twi1", "twi0", "uart1", "pwm0_11", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA3: ["gpio_in", "gpio_out", "csi", "pwm0_6", "twi0", "uart1", "clk", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA4: ["gpio_in", "gpio_out", "csi", "pwm0_7", "twi0", "uart1", "clk", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA5: ["gpio_in", "gpio_out", "mipia", "uart2", "pwm0_8", "uart3", "twi1", "spi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA6: ["gpio_in", "gpio_out", "mipia", "uart2", "pwm0_9", "uart3", "twi1", "spi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA7: ["gpio_in", "gpio_out", "mipia", "uart2", "uart1", "pwm0_0", "twi0", "spi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA8: ["gpio_in", "gpio_out", "mipia", "uart2", "uart1", "pwm0_1", "twi0", "spi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA9: ["gpio_in", "gpio_out", "mipib", "twi0", "twi1", "pwm0_2", "uart3", "spi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC0: ["gpio_in", "gpio_out", "sdc0", "rjtag", "uart3", "pwm0_0", "twi2", "dbg", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC1: ["gpio_in", "gpio_out", "sdc0", "rjtag", "uart3", "pwm0_1", "twi2", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC10: ["gpio_in", "gpio_out", "spif", "spi0", "twi2", "twi0", "pwm0_10", "sdc0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC11: ["gpio_in", "gpio_out", "spif", "spi0", "boot", "twi0", "pwm0_11", "sdc0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC12: ["gpio_in", "gpio_out", "rjtag", "twi1", "pwm0_6", "spi1", "i2s0_mclk", "sdc1", "test", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC13: ["gpio_in", "gpio_out", "rjtag", "twi1", "pwm0_7", "spi1", "i2s0_bclk", "sdc1", "test", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC14: ["gpio_in", "gpio_out", "rjtag", "null", "pwm0_8", "spi1", "i2s0_lrck", "sdc1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC15: ["gpio_in", "gpio_out", "rjtag", "pwm0_11", "pwm0_9", "spi1", "i2s0_din0", "sdc1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC16: ["gpio_in", "gpio_out", "null", "null", "pwm0_10", "spi1", "i2s0_dout0", "csi", "sdc0", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC2: ["gpio_in", "gpio_out", "sdc0", "uart0", "uart3", "pwm0_2", "twi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC3: ["gpio_in", "gpio_out", "sdc0", "rjtag", "uart3", "pwm0_3", "twi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC4: ["gpio_in", "gpio_out", "sdc0", "uart0", "uart2", "pwm0_4", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC5: ["gpio_in", "gpio_out", "sdc0", "rjtag", "uart2", "pwm0_5", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC6: ["gpio_in", "gpio_out", "spif", "spi0", "pwm0_6", "twi2", "fem", "sdc0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC7: ["gpio_in", "gpio_out", "spif", "spi0", "pwm0_7", "twi2", "fem", "sdc0", "csi", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC8: ["gpio_in", "gpio_out", "spif", "spi0", "boot", "pwm0_8", "null", "sdc0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC9: ["gpio_in", "gpio_out", "spif", "spi0", "twi2", "pwm0_9", "null", "sdc0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD0: ["gpio_in", "gpio_out", "lcd", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD1: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_0", "sdc1", "twi0", "spi1", "spi2", "null", "null", "null", "debug0", "eint", "io_disabled"],
                PD10: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_9", "uart1", "twi2", "lcds_ctl", "i2s0_dout3", "i2s0_din3", "null", "null", "debug9", "eint", "io_disabled"],
                PD11: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_10", "i2s0_mclk", "pwm0_0", "lcds_ctl", "null", "null", "null", "null", "debug10", "eint", "io_disabled"],
                PD12: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_2", "spi1", "i2s0_bclk", "clk", "lcds_ctl", "null", "null", "null", "null", "debug11", "eint", "io_disabled"],
                PD13: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_3", "spi1", "i2s0_lrck", "twi1", "tcon", "null", "null", "null", "debug", "debug12", "eint", "io_disabled"],
                PD14: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_4", "spi1", "i2s0_din0", "twi1", "spi1", "spi2", "null", "null", "debug", "debug13", "eint", "io_disabled"],
                PD15: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_5", "spi1", "i2s0_dout0", "twi2", "spi1", "spi2", "null", "null", "debug", "debug14", "eint", "io_disabled"],
                PD16: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_6", "spi1", "csi", "twi2", "spi1", "spi2", "null", "null", "debug", "debug15", "eint", "io_disabled"],
                PD17: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_7", "pwm0_11", "sdc1", "fem", "spi1", "spi2", "null", "null", "null", "null", "eint", "io_disabled"],
                PD18: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_8", "twi1", "sdc1", "fem", "spi1", "spi2", "null", "null", "null", "null", "eint", "io_disabled"],
                PD19: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_9", "twi1", "sdc1", "uart0", "spi1", "spi2", "null", "null", "null", "null", "eint", "io_disabled"],
                PD2: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_1", "sdc1", "twi0", "spi1", "spi2", "null", "null", "null", "debug1", "eint", "io_disabled"],
                PD20: ["gpio_in", "gpio_out", "lcd", "ncsi", "pwm0_10", "pwm0_8", "sdc1", "uart0", "spi1", "clk", "null", "null", "null", "null", "eint", "io_disabled"],
                PD21: ["gpio_in", "gpio_out", "null", "null", "pwm0_11", "pwm0_9", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD22: ["gpio_in", "gpio_out", "lcd", "uart0", "rjtag", "pwm0_10", "sdc1", "fem", "twi2", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD23: ["gpio_in", "gpio_out", "tcon", "uart0", "rjtag", "pwm0_11", "sdc1", "fem", "twi2", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD3: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_2", "sdc1", "twi1", "spi1", "spi2", "null", "null", "null", "debug2", "eint", "io_disabled"],
                PD4: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_3", "sdc1", "twi1", "spi1", "spi2", "null", "null", "null", "debug3", "eint", "io_disabled"],
                PD5: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_4", "sdc1", "spi1", "spi1_hold", "spi2", "null", "null", "null", "debug4", "eint", "io_disabled"],
                PD6: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_5", "sdc1", "spi1", "spi1_wp", "spi2", "null", "null", "null", "debug5", "eint", "io_disabled"],
                PD7: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_6", "uart1", "spi1", "rjtag", "i2s0_dout0", "i2s0_din0", "null", "null", "debug6", "eint", "io_disabled"],
                PD8: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_7", "uart1", "spi1", "rjtag", "i2s0_dout1", "i2s0_din1", "null", "null", "debug7", "eint", "io_disabled"],
                PD9: ["gpio_in", "gpio_out", "lcd", "ncsi", "rmii", "pwm0_8", "uart1", "twi2", "lcds_ctl", "i2s0_dout2", "i2s0_din2", "null", "null", "debug8", "eint", "io_disabled"]
            },
        },
        rtc_pio: {
            reg_base: 0x42000540,
            version: 2,
            pin_bank_num: {
                PL: 8
            },
            pin_mux: {
                PL0: ["gpio_in", "gpio_out", "twi1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL1: ["gpio_in", "gpio_out", "twi1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL2: ["gpio_in", "gpio_out", "twi2", "uart3", "uart2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL3: ["gpio_in", "gpio_out", "twi2", "uart3", "uart2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL4: ["gpio_in", "gpio_out", "twi0", "uart0", "uart2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL5: ["gpio_in", "gpio_out", "twi0", "uart0", "uart2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL6: ["gpio_in", "gpio_out", "csi", "null", "null", "null", "mco", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL7: ["gpio_in", "gpio_out", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
    }
};