import type { ChipInfo } from '../Drivers/Types';

export const aw1890: ChipInfo = {
    id: '1890',
    chipMark: {
        "A523": 0x218B,
        "A527": 0x210C,
        "T527": 0x5f30,
    },
    pinctrl: {
        pio: {
            reg_base: 0x02000000,
            version: 2,
            pin_bank_num: {
                PB: 15,
                PC: 17,
                PD: 24,
                PE: 16,
                PF: 7,
                PG: 15,
                PH: 20,
                PI: 17,
                PJ: 28
            },
            pin_mux: {
                PB0: ["gpio_in", "gpio_out", "uart2", "spi2", "jtag", "lcd0", "pwm0_6", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB1: ["gpio_in", "gpio_out", "uart2", "spi2", "jtag", "lcd0", "pwm0_7", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB10: ["gpio_in", "gpio_out", "uart0", "twi0", "pwm0_1", "i2s0_din", "i2s0_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB11: ["gpio_in", "gpio_out", "twi5", "uart7", "spi1", "pwm0_2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB12: ["gpio_in", "gpio_out", "twi5", "uart7", "spi1", "pwm0_3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB13: ["gpio_in", "gpio_out", "twi4", "uart7", "spi1", "pwm0_4", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB14: ["gpio_in", "gpio_out", "twi4", "uart7", "spi1", "pwm0_5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB2: ["gpio_in", "gpio_out", "uart2", "spi2", "jtag", "lcd0", "test", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB3: ["gpio_in", "gpio_out", "uart2", "spi2", "jtag", "lcd0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB4: ["gpio_in", "gpio_out", "twi1", "i2s0", "trace", "pwm0_8", "hscl", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB5: ["gpio_in", "gpio_out", "twi1", "i2s0", "trace", "pwm0_9", "hsda", "test", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB6: ["gpio_in", "gpio_out", "null", "i2s0", "trace", "pwm0_10", "hcec", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB7: ["gpio_in", "gpio_out", "owa", "i2s0_dout", "i2s0_din", "lcd0", "pwm0_11", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB8: ["gpio_in", "gpio_out", "owa", "i2s0_din", "i2s0_dout", "lcd0", "pwm0_0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB9: ["gpio_in", "gpio_out", "uart0", "twi0", "trace", "i2s0_din", "i2s0_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC0: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC1: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC10: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC11: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC12: ["gpio_in", "gpio_out", "nand0", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC13: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC14: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC15: ["gpio_in", "gpio_out", "nand0", "sdc2", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC16: ["gpio_in", "gpio_out", "nand0", "sdc2", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC2: ["gpio_in", "gpio_out", "nand0", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC3: ["gpio_in", "gpio_out", "nand0", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC4: ["gpio_in", "gpio_out", "nand0", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC5: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC6: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC7: ["gpio_in", "gpio_out", "nand0", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC8: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC9: ["gpio_in", "gpio_out", "nand0", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD0: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD1: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD10: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm0_10", "spi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD11: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm0_11", "spi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD12: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm0_12", "spi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD13: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm0_13", "spi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD14: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm0_14", "uart3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD15: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm0_15", "uart3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD16: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm1_0", "uart3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD17: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm1_1", "uart3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD18: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm1_2", "uart4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD19: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "pwm1_3", "uart4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD2: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD20: ["gpio_in", "gpio_out", "lcd0", "pwm0_2", "uart2", "uart7", "uart4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD21: ["gpio_in", "gpio_out", "lcd0", "pwm0_3", "uart2", "uart7", "uart4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD22: ["gpio_in", "gpio_out", "pwm0_1", "spi1", "uart2", "uart7", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD23: ["gpio_in", "gpio_out", "pwm0_0", "spi1", "uart2", "uart7", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD3: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD4: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_4", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD5: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD6: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_6", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD7: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_7", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD8: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_8", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD9: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "pwm0_9", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE0: ["gpio_in", "gpio_out", "mipi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE1: ["gpio_in", "gpio_out", "twi2", "uart4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE10: ["gpio_in", "gpio_out", "mipi3", "pwm0_3", "null", "null", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE11: ["gpio_in", "gpio_out", "twi1", "uart5", "spi2", "uart6", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE12: ["gpio_in", "gpio_out", "twi1", "uart5", "spi2", "uart6", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE13: ["gpio_in", "gpio_out", "twi4", "uart5", "spi2", "uart6", "csi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE14: ["gpio_in", "gpio_out", "twi4", "uart5", "spi2", "uart6", "csi1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE15: ["gpio_in", "gpio_out", "mipi2", "pwm0_2", "null", "null", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE2: ["gpio_in", "gpio_out", "twi2", "uart4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE3: ["gpio_in", "gpio_out", "twi3", "uart4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE4: ["gpio_in", "gpio_out", "twi3", "uart4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE5: ["gpio_in", "gpio_out", "mipi1", "pll0", "i2s2", "ledc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE6: ["gpio_in", "gpio_out", "null", "bist0", "i2s2", "lcd0", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE7: ["gpio_in", "gpio_out", "null", "bist1", "i2s2", "lcd1", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE8: ["gpio_in", "gpio_out", "null", "bist2", "i2s2", "lcd2", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE9: ["gpio_in", "gpio_out", "null", "bist3", "i2s2", "null", "ncsi", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF0: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "i2s3_din", "i2s3_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF1: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "i2s3_dout", "i2s3_din", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF2: ["gpio_in", "gpio_out", "sdc0", "uart0", "null", "i2s3_din", "i2s3_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF3: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "i2s3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF4: ["gpio_in", "gpio_out", "sdc0", "uart0", "null", "i2s3_din", "i2s3_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF5: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "i2s3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF6: ["gpio_in", "gpio_out", "null", "null", "null", "i2s3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG0: ["gpio_in", "gpio_out", "sdc1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG1: ["gpio_in", "gpio_out", "sdc1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG10: ["gpio_in", "gpio_out", "null", "i2s1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG11: ["gpio_in", "gpio_out", "null", "i2s1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG12: ["gpio_in", "gpio_out", "null", "i2s1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG13: ["gpio_in", "gpio_out", "null", "i2s1_dout", "i2s1_din", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG14: ["gpio_in", "gpio_out", "null", "i2s1_din", "i2s1_dout", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG2: ["gpio_in", "gpio_out", "sdc1", "pcie", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG3: ["gpio_in", "gpio_out", "sdc1", "pcie", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG4: ["gpio_in", "gpio_out", "sdc1", "pcie", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG5: ["gpio_in", "gpio_out", "sdc1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG6: ["gpio_in", "gpio_out", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG7: ["gpio_in", "gpio_out", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG8: ["gpio_in", "gpio_out", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG9: ["gpio_in", "gpio_out", "uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH0: ["gpio_in", "gpio_out", "twi0", "null", "null", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH1: ["gpio_in", "gpio_out", "twi0", "null", "null", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH10: ["gpio_in", "gpio_out", "dmic", "spi2", "i2s2", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH11: ["gpio_in", "gpio_out", "dmic", "spi2", "i2s2_dout", "i2s2_din", "pcie", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH12: ["gpio_in", "gpio_out", "dmic", "twi3", "i2s2_din", "i2s2_dout", "pcie", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH13: ["gpio_in", "gpio_out", "null", "twi3", "i2s3", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH14: ["gpio_in", "gpio_out", "null", "null", "i2s3", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH15: ["gpio_in", "gpio_out", "null", "null", "i2s3", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH16: ["gpio_in", "gpio_out", "null", "i2s3_dout", "i2s3_din", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH17: ["gpio_in", "gpio_out", "null", "i2s3_dout", "i2s3_din", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH18: ["gpio_in", "gpio_out", "cir", "i2s3_dout", "i2s3_din", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH19: ["gpio_in", "gpio_out", "cir", "i2s3_dout", "i2s3_din", "ledc", "pcie", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH2: ["gpio_in", "gpio_out", "twi1", "cpu", "i2s2_din", "gmac0", "i2s2_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH3: ["gpio_in", "gpio_out", "twi1", "cir", "i2s2_din", "gmac0", "i2s2_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH4: ["gpio_in", "gpio_out", "uart3", "spi1", "cpu", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH5: ["gpio_in", "gpio_out", "uart3", "spi1", "ledc", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH6: ["gpio_in", "gpio_out", "uart3", "spi1", "owa", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH7: ["gpio_in", "gpio_out", "uart3", "spi1", "owa", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH8: ["gpio_in", "gpio_out", "dmic", "spi2", "i2s2_mclk", "i2s2_din", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH9: ["gpio_in", "gpio_out", "dmic", "spi2", "i2s2", "gmac0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI0: ["gpio_in", "gpio_out", "twi4", "uart4", "pwm0_1", "i2s2_din", "i2s2_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI1: ["gpio_in", "gpio_out", "twi4", "uart4", "pwm0_2", "i2s2_din", "i2s2_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI10: ["gpio_in", "gpio_out", "owa", "dmic", "pwm0_11", "i2s2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI11: ["gpio_in", "gpio_out", "uart3", "dmic", "pwm0_12", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI12: ["gpio_in", "gpio_out", "uart3", "null", "pwm0_13", "spi2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI13: ["gpio_in", "gpio_out", "uart6", "dmic", "pwm0_14", "i2s2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI14: ["gpio_in", "gpio_out", "uart6", "dmic", "pwm0_15", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI15: ["gpio_in", "gpio_out", "uart3", "twi2", "pwm1_0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI16: ["gpio_in", "gpio_out", "uart3", "twi2", "pwm1_1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI2: ["gpio_in", "gpio_out", "uart5", "spi1", "pwm0_3", "i2s2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI3: ["gpio_in", "gpio_out", "uart5", "spi1", "pwm0_4", "i2s2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI4: ["gpio_in", "gpio_out", "uart5", "spi1", "pwm0_5", "i2s2_dout", "i2s2_din", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI5: ["gpio_in", "gpio_out", "uart5", "spi1", "pwm0_6", "i2s2_din", "i2s2_dout", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI6: ["gpio_in", "gpio_out", "uart6", "uart4", "pwm0_7", "spi2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI7: ["gpio_in", "gpio_out", "uart6", "uart4", "pwm0_8", "spi2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI8: ["gpio_in", "gpio_out", "twi5", "cir", "pwm0_9", "spi2", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI9: ["gpio_in", "gpio_out", "twi5", "dmic", "pwm0_10", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ0: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ1: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ10: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ11: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ12: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ13: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ14: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ15: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ16: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ17: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ18: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ19: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ2: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ20: ["gpio_in", "gpio_out", "lcd1", "uart2", "uart3", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ21: ["gpio_in", "gpio_out", "lcd1", "uart2", "uart3", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ22: ["gpio_in", "gpio_out", "lcd1", "uart2", "uart3", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ23: ["gpio_in", "gpio_out", "lcd1", "uart2", "uart3", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ24: ["gpio_in", "gpio_out", "lcd1", "twi4", "uart4", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ25: ["gpio_in", "gpio_out", "lcd1", "twi4", "uart4", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ26: ["gpio_in", "gpio_out", "lcd1", "twi5", "uart4", "spi0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ27: ["gpio_in", "gpio_out", "lcd1", "twi5", "uart4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ3: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ4: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ5: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ6: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ7: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ8: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ9: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "gmac1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
        // PK bank has a special offset at 0x500, separate from other banks
        pk_pio: {
            reg_base: 0x02000500,
            version: 2,
            pin_bank_num: {
                PK: 24
            },
            // PK is the only bank in this controller, so offset is 0
            bankOffsetHook: () => 0,
            pin_mux: {
                PK0: ["gpio_in", "gpio_out", "mcsia", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK1: ["gpio_in", "gpio_out", "mcsia", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK10: ["gpio_in", "gpio_out", "mcsib", "twi3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK11: ["gpio_in", "gpio_out", "mcsib", "twi3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK12: ["gpio_in", "gpio_out", "mcsic", "uart7", "twi4", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK13: ["gpio_in", "gpio_out", "mcsic", "uart7", "twi4", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK14: ["gpio_in", "gpio_out", "mcsic", "uart7", "uart5", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK15: ["gpio_in", "gpio_out", "mcsic", "uart7", "uart5", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK16: ["gpio_in", "gpio_out", "mcsic", "twi5", "uart5", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK17: ["gpio_in", "gpio_out", "mcsic", "twi5", "uart5", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK18: ["gpio_in", "gpio_out", "mcsid", "mipi0", "uart6", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK19: ["gpio_in", "gpio_out", "mcsid", "twi2", "uart6", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK2: ["gpio_in", "gpio_out", "mcsia", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK20: ["gpio_in", "gpio_out", "mcsid", "twi2", "uart6", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK21: ["gpio_in", "gpio_out", "mcsid", "mipi1", "uart6", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK22: ["gpio_in", "gpio_out", "mcsid", "twi3", "pwm0_6", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK23: ["gpio_in", "gpio_out", "mcsid", "twi3", "pwm0_7", "ncsi", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK3: ["gpio_in", "gpio_out", "mcsia", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK4: ["gpio_in", "gpio_out", "mcsia", "twi2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK5: ["gpio_in", "gpio_out", "mcsia", "twi2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK6: ["gpio_in", "gpio_out", "mcsib", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK7: ["gpio_in", "gpio_out", "mcsib", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK8: ["gpio_in", "gpio_out", "mcsib", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK9: ["gpio_in", "gpio_out", "mcsib", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
        rtc_pio: {
            reg_base: 0x07022000,
            version: 2,
            pin_bank_num: {
                PL: 14,
                PM: 6
            },
            pin_mux: {
                PL0: ["gpio_in", "gpio_out", "s_twi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL1: ["gpio_in", "gpio_out", "s_twi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL10: ["gpio_in", "gpio_out", "s_pwm0_0", "d_jtag", "r_jtag", "dmic", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL11: ["gpio_in", "gpio_out", "s_cir", "d_jtag", "r_jtag", "s_pwm0_1", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL12: ["gpio_in", "gpio_out", "s_twi2", "mcu_pwm0_6", "s_uart0", "null", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL13: ["gpio_in", "gpio_out", "s_twi2", "mcu_pwm0_7", "s_uart0", "null", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL2: ["gpio_in", "gpio_out", "s_uart0", "s_uart1", "mcu_pwm0_0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL3: ["gpio_in", "gpio_out", "s_uart0", "s_uart1", "mcu_pwm0_1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL4: ["gpio_in", "gpio_out", "s_jtag", "null", "mcu_pwm0_2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL5: ["gpio_in", "gpio_out", "s_jtag", "null", "mcu_pwm0_3", "i2s0", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL6: ["gpio_in", "gpio_out", "s_jtag", "mcu_pwm0_4", "i2s0_din", "i2s0_dout", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL7: ["gpio_in", "gpio_out", "s_jtag", "mcu_pwm0_5", "i2s0_dout", "i2s0_din", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL8: ["gpio_in", "gpio_out", "s_twi1", "d_jtag", "r_jtag", "i2s0", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL9: ["gpio_in", "gpio_out", "s_twi1", "d_jtag", "r_jtag", "s_pwm0_1", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM0: ["gpio_in", "gpio_out", "s_uart0", "s_uart1", "mcu_pwm0_0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM1: ["gpio_in", "gpio_out", "s_uart0", "s_uart1", "mcu_pwm0_1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM2: ["gpio_in", "gpio_out", "s_twi1", "r_jtag", "mcu_pwm0_4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM3: ["gpio_in", "gpio_out", "s_twi1", "r_jtag", "mcu_pwm0_5", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM4: ["gpio_in", "gpio_out", "mcu_pwm0_6", "r_jtag", "s_twi2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM5: ["gpio_in", "gpio_out", "s_cir", "r_jtag", "s_twi2", "mcu_pwm0_7", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
    }
};