import type { ChipInfo } from '../Drivers/Types';

export const aw1922: ChipInfo = {
    id: '1922',
    chipMark: {
        "T153": 0x2000,
        "T153MX-BCX": 0x7700,
        "MR153": 0x3000,
        "AW1922": 0x0
    },
    pinctrl: {
        pio: {
            reg_base: 0x3604000,
            version: 3,
            pin_bank_num: {
                PA: 24,
                PB: 15,
                PC: 12,
                PD: 24,
                PE: 10,
                PF: 7,
                PG: 16,
                PJ: 16,
                PK: 12
            },
            pin_mux: {
                PA0: ["gpio_in", "gpio_out", "gpadc2", "tp", "null", "null", "lbus", "lbus_lbe2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA1: ["gpio_in", "gpio_out", "gpadc2", "tp", "null", "null", "lbus", "lbus_dp1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA10: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_ic", "null", "lcd", "null", "null", "null", "null", "eint", "io_disabled"],
                PA11: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_id", "null", "lcd", "null", "null", "null", "null", "eint", "io_disabled"],
                PA12: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_ie", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA13: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_if", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA14: ["gpio_in", "gpio_out", "gpadc1", "null", "rgmii0", "ncsi", "lbus", "uart6", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA15: ["gpio_in", "gpio_out", "gpadc1", "null", "rgmii0", "ncsi", "lbus", "uart6", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA16: ["gpio_in", "gpio_out", "gpadc1", "null", "rgmii0", "ncsi", "lbus", "twi3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA17: ["gpio_in", "gpio_out", "gpadc1", "null", "rgmii0", "ncsi", "lbus", "twi3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA18: ["gpio_in", "gpio_out", "gpadc1", "null", "rgmii0", "ncsi", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA19: ["gpio_in", "gpio_out", "gpadc1", "null", "rgmii0", "ncsi", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA2: ["gpio_in", "gpio_out", "gpadc2", "tp", "null", "null", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA20: ["gpio_in", "gpio_out", "gpadc1", "null", "null", "ncsi", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA21: ["gpio_in", "gpio_out", "gpadc1", "null", "null", "ncsi", "lbus", "spi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA22: ["gpio_in", "gpio_out", "gpadc1", "null", "null", "ncsi", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA23: ["gpio_in", "gpio_out", "gpadc1", "null", "null", "ncsi", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA3: ["gpio_in", "gpio_out", "gpadc2", "tp", "null", "null", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA4: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA5: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA6: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_i8", "null", "lcd", "null", "null", "null", "null", "eint", "io_disabled"],
                PA7: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_i9", "null", "lcd", "null", "null", "null", "null", "eint", "io_disabled"],
                PA8: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_ia", "null", "lcd", "null", "null", "null", "null", "eint", "io_disabled"],
                PA9: ["gpio_in", "gpio_out", "gpadc0", "null", "rgmii0", "ncsi", "lbus", "pwmcs_ib", "lbus_lbe3", "lcd", "null", "null", "null", "null", "eint", "io_disabled"],
                PB0: ["gpio_in", "gpio_out", "uart2", "spi3", "jtag", "pwm0_6", "null", "rjtag", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB1: ["gpio_in", "gpio_out", "uart2", "spi3", "jtag", "pwm0_7", "null", "rjtag", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB10: ["gpio_in", "gpio_out", "uart0", "i2s0_din3", "i2s0_dout3", "pwm0_1", "twi0", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB11: ["gpio_in", "gpio_out", "twi5", "uart7", "spi3", "pwm0_2", "watchdog", "uart8", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB12: ["gpio_in", "gpio_out", "twi5", "uart7", "spi3", "pwm0_3", "pll", "null", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB13: ["gpio_in", "gpio_out", "twi4", "uart7", "spi3", "pwm0_4", "ir2", "clk", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB14: ["gpio_in", "gpio_out", "twi4", "uart7", "spi3", "pwm0_5", "ir3", "clk", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB2: ["gpio_in", "gpio_out", "uart2", "spi3", "jtag", "twi2", "null", "rjtag", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB3: ["gpio_in", "gpio_out", "uart2", "spi3", "jtag", "twi2", "null", "rjtag", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB4: ["gpio_in", "gpio_out", "twi1", "i2s0_mclk", "spi3", "pwm1_0", "ir0", "uart8", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB5: ["gpio_in", "gpio_out", "twi1", "i2s0_bclk", "spi3", "pwm1_1", "ir1", "uart8", "null", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB6: ["gpio_in", "gpio_out", "null", "i2s0_lrck", "null", "pwm1_2", "ir", "uart8", "twi0", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB7: ["gpio_in", "gpio_out", "owa", "i2s0_dout0", "i2s0_din1", "pwm1_3", "null", "uart8", "twi0", "rgmii2", "null", "null", "null", "null", "eint", "io_disabled"],
                PB8: ["gpio_in", "gpio_out", "owa", "i2s0_din0", "i2s0_dout1", "pwm0_0", "null", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB9: ["gpio_in", "gpio_out", "uart0", "i2s0_din2", "i2s0_dout2", "null", "twi0", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC0: ["gpio_in", "gpio_out", "sdc2", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC1: ["gpio_in", "gpio_out", "sdc2", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC10: ["gpio_in", "gpio_out", "sdc2", "null", "spif0", "uart5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC11: ["gpio_in", "gpio_out", "sdc2", "null", "null", "uart5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC2: ["gpio_in", "gpio_out", "sdc2", "spi0", "spif0", "boot", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC3: ["gpio_in", "gpio_out", "sdc2", "spi0", "spif0", "boot", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC4: ["gpio_in", "gpio_out", "sdc2", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC5: ["gpio_in", "gpio_out", "sdc2", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC6: ["gpio_in", "gpio_out", "sdc2", "spi0", "spif0", "null", "uart6", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC7: ["gpio_in", "gpio_out", "sdc2", "null", "spif0", "null", "uart6", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC8: ["gpio_in", "gpio_out", "sdc2", "null", "spif0", "uart5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC9: ["gpio_in", "gpio_out", "sdc2", "null", "spif0", "uart5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD0: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_0", "uart2", "uart9", "lbus", "pwmcs_o0", "null", "null", "null", "null", "eint", "io_disabled"],
                PD1: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_1", "uart2", "uart9", "lbus", "pwmcs_o1", "null", "null", "null", "null", "eint", "io_disabled"],
                PD10: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_2", "dmic", "uart8", "lbus", "pwmcs_oa", "null", "null", "null", "null", "eint", "io_disabled"],
                PD11: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_3", "dmic", "uart8", "lbus", "pwmcs_ob", "null", "null", "null", "null", "eint", "io_disabled"],
                PD12: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_4", "dmic", "uart8", "lbus", "pwmcs_oc", "null", "null", "null", "null", "eint", "io_disabled"],
                PD13: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_5", "dmic", "uart8", "lbus", "pwmcs_od", "null", "null", "null", "null", "eint", "io_disabled"],
                PD14: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_6", "uart3", "uart8", "lbus", "pwmcs_oe", "null", "null", "null", "null", "eint", "io_disabled"],
                PD15: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_7", "uart3", "uart8", "lbus", "pwmcs_of", "null", "null", "null", "null", "eint", "io_disabled"],
                PD16: ["gpio_in", "gpio_out", "lcd", "lvds1", "null", "pwm2_0", "uart3", "uart8", "lbus", "pwmcs_i0", "null", "null", "null", "null", "eint", "io_disabled"],
                PD17: ["gpio_in", "gpio_out", "lcd", "lvds1", "null", "pwm2_1", "uart3", "uart8", "lbus", "pwmcs_i1", "null", "null", "null", "null", "eint", "io_disabled"],
                PD18: ["gpio_in", "gpio_out", "lcd", "lvds1", "twi5", "pwm2_2", "null", "null", "lbus", "pwmcs_i2", "null", "null", "null", "null", "eint", "io_disabled"],
                PD19: ["gpio_in", "gpio_out", "lcd", "lvds1", "twi5", "pwm2_3", "null", "null", "lbus", "pwmcs_i3", "null", "null", "null", "null", "eint", "io_disabled"],
                PD2: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_2", "uart2", "uart9", "lbus", "pwmcs_o2", "null", "null", "null", "null", "eint", "io_disabled"],
                PD20: ["gpio_in", "gpio_out", "lcd", "pwm2_4", "uart3", "twi5", "null", "null", "lbus", "pwmcs_i4", "null", "null", "null", "null", "eint", "io_disabled"],
                PD21: ["gpio_in", "gpio_out", "lcd", "pwm2_5", "uart3", "twi5", "null", "null", "lbus", "pwmcs_i5", "null", "null", "null", "null", "eint", "io_disabled"],
                PD22: ["gpio_in", "gpio_out", "null", "pwm2_6", "uart3", "twi4", "twi0", "csi0", "lbus", "pwmcs_i6", "null", "null", "null", "null", "eint", "io_disabled"],
                PD23: ["gpio_in", "gpio_out", "null", "pwm2_7", "uart3", "twi4", "twi0", "csi1", "lbus", "pwmcs_i7", "null", "null", "null", "null", "eint", "io_disabled"],
                PD3: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_3", "uart2", "uart9", "lbus", "pwmcs_o3", "null", "null", "null", "null", "eint", "io_disabled"],
                PD4: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_4", "uart4", "uart6", "lbus", "pwmcs_o4", "null", "null", "null", "null", "eint", "io_disabled"],
                PD5: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_5", "uart4", "uart6", "lbus", "pwmcs_o5", "null", "null", "null", "null", "eint", "io_disabled"],
                PD6: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_6", "uart4", "uart6", "lbus", "pwmcs_o6", "null", "null", "null", "null", "eint", "io_disabled"],
                PD7: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_7", "uart4", "uart6", "lbus", "pwmcs_o7", "null", "null", "null", "null", "eint", "io_disabled"],
                PD8: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm1_0", "null", "null", "lbus", "pwmcs_o8", "null", "null", "null", "null", "eint", "io_disabled"],
                PD9: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm1_1", "dmic", "null", "lbus", "pwmcs_o9", "null", "null", "null", "null", "eint", "io_disabled"],
                PE0: ["gpio_in", "gpio_out", "mcsi0", "null", "ncsi", "clk", "null", "dmic", "null", "sdc3", "null", "null", "null", "null", "eint", "io_disabled"],
                PE1: ["gpio_in", "gpio_out", "twi1", "null", "ncsi", "null", "spi2", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE2: ["gpio_in", "gpio_out", "twi1", "pwm0_3", "ncsi", "null", "spi2", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE3: ["gpio_in", "gpio_out", "twi2", "uart5", "ncsi", "uart6", "spi2", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE4: ["gpio_in", "gpio_out", "twi2", "uart5", "ncsi", "uart6", "spi2", "dmic", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE5: ["gpio_in", "gpio_out", "mcsi1", "uart5", "ncsi", "uart6", "spi2", "null", "null", "sdc3", "null", "null", "null", "null", "eint", "io_disabled"],
                PE6: ["gpio_in", "gpio_out", "twi3", "uart5", "ncsi", "uart6", "spi2", "null", "null", "sdc3", "null", "null", "null", "null", "eint", "io_disabled"],
                PE7: ["gpio_in", "gpio_out", "twi3", "pwm0_2", "ncsi", "null", "spi2", "null", "null", "sdc3", "null", "null", "null", "null", "eint", "io_disabled"],
                PE8: ["gpio_in", "gpio_out", "mcsi2", "pwm0_4", "csi0", "clk", "spi2", "null", "null", "sdc3", "null", "null", "null", "null", "eint", "io_disabled"],
                PE9: ["gpio_in", "gpio_out", "tcon", "pwm0_5", "csi1", "null", "null", "null", "null", "sdc3", "null", "null", "null", "null", "eint", "io_disabled"],
                PF0: ["gpio_in", "gpio_out", "sdc0", "jtag", "uart1", "null", "null", "rjtag", "ir0", "lbus", "null", "null", "null", "null", "eint", "io_disabled"],
                PF1: ["gpio_in", "gpio_out", "sdc0", "jtag", "uart1", "null", "null", "rjtag", "ir1", "lbus", "null", "null", "null", "null", "eint", "io_disabled"],
                PF2: ["gpio_in", "gpio_out", "sdc0", "uart0", "dmic", "null", "spi3", "null", "ir2", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF3: ["gpio_in", "gpio_out", "sdc0", "jtag", "dmic", "null", "spi3", "rjtag", "ir3", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF4: ["gpio_in", "gpio_out", "sdc0", "uart0", "dmic", "null", "spi3", "null", "ir", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF5: ["gpio_in", "gpio_out", "sdc0", "jtag", "dmic", "null", "spi3", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF6: ["gpio_in", "gpio_out", "null", "null", "dmic", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG0: ["gpio_in", "gpio_out", "sdc1", "null", "uart8", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG1: ["gpio_in", "gpio_out", "sdc1", "null", "uart8", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG10: ["gpio_in", "gpio_out", "uart4", "i2s1_mclk", "twi2", "rgmii1", "i2s2_din0", "i2s2_dout1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG11: ["gpio_in", "gpio_out", "uart4", "i2s1_bclk", "twi2", "rgmii1", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG12: ["gpio_in", "gpio_out", "uart4", "i2s1_lrck", "null", "rgmii1", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG13: ["gpio_in", "gpio_out", "uart4", "i2s1_dout0", "i2s1_din1", "rgmii1", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG14: ["gpio_in", "gpio_out", "null", "i2s1_din0", "i2s1_dout1", "rgmii1", "dmic", "null", "lbus", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG15: ["gpio_in", "gpio_out", "null", "null", "null", "rgmii1", "dmic", "null", "lbus", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG2: ["gpio_in", "gpio_out", "sdc1", "null", "uart8", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG3: ["gpio_in", "gpio_out", "sdc1", "null", "uart8", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG4: ["gpio_in", "gpio_out", "sdc1", "null", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG5: ["gpio_in", "gpio_out", "sdc1", "null", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG6: ["gpio_in", "gpio_out", "uart1", "twi4", "uart9", "rgmii1", "i2s2_mclk", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG7: ["gpio_in", "gpio_out", "uart1", "twi4", "uart9", "rgmii1", "i2s2_bclk", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG8: ["gpio_in", "gpio_out", "uart1", "twi5", "uart9", "rgmii1", "i2s2_lrck", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG9: ["gpio_in", "gpio_out", "uart1", "twi5", "uart9", "rgmii1", "i2s2_dout0", "i2s2_din1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ0: ["gpio_in", "gpio_out", "pwm2_0", "i2s2_mclk", "twi4", "rgmii0", "dmic", "uart5", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ1: ["gpio_in", "gpio_out", "pwm2_1", "i2s2_bclk", "twi4", "rgmii0", "dmic", "uart5", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ10: ["gpio_in", "gpio_out", "pwm2_10", "i2s1_dout0", "i2s1_din1", "rgmii0", "null", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ11: ["gpio_in", "gpio_out", "pwm2_11", "i2s1_din0", "i2s1_dout1", "rgmii0", "null", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ12: ["gpio_in", "gpio_out", "pwm2_12", "null", "ir0", "rgmii0", "twi0", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ13: ["gpio_in", "gpio_out", "pwm2_13", "null", "ir1", "rgmii0", "twi0", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ14: ["gpio_in", "gpio_out", "null", "null", "ir2", "rgmii0", "twi5", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ15: ["gpio_in", "gpio_out", "null", "null", "ir3", "rgmii0", "twi5", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ2: ["gpio_in", "gpio_out", "pwm2_2", "i2s2_lrck", "null", "rgmii0", "dmic", "uart5", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ3: ["gpio_in", "gpio_out", "pwm2_3", "i2s2_dout0", "i2s2_din1", "rgmii0", "dmic", "uart5", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ4: ["gpio_in", "gpio_out", "pwm2_4", "i2s2_din0", "i2s2_dout1", "rgmii0", "dmic", "uart7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ5: ["gpio_in", "gpio_out", "pwm2_5", "i2s2_din2", "i2s2_dout2", "rgmii0", "null", "uart7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ6: ["gpio_in", "gpio_out", "pwm2_6", "i2s2_din3", "i2s2_dout3", "rgmii0", "null", "uart7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ7: ["gpio_in", "gpio_out", "pwm2_7", "i2s1_mclk", "null", "rgmii0", "null", "uart7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ8: ["gpio_in", "gpio_out", "pwm2_8", "i2s1_bclk", "ledc", "rgmii0", "null", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ9: ["gpio_in", "gpio_out", "pwm2_9", "i2s1_lrck", "ir", "rgmii0", "null", "uart2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK0: ["gpio_in", "gpio_out", "null", "mcsia", "null", "uart7", "twi1", "ncsi", "lbus", "i2s1_mclk", "null", "null", "null", "null", "eint", "io_disabled"],
                PK1: ["gpio_in", "gpio_out", "null", "mcsia", "null", "uart7", "twi1", "ncsi", "lbus", "i2s1_bclk", "null", "null", "null", "null", "eint", "io_disabled"],
                PK10: ["gpio_in", "gpio_out", "null", "mcsib", "null", "twi3", "pwm0_6", "ncsi", "lbus", "uart3", "null", "null", "null", "null", "eint", "io_disabled"],
                PK11: ["gpio_in", "gpio_out", "null", "mcsib", "null", "twi3", "pwm0_7", "ncsi", "lbus", "uart3", "null", "null", "null", "null", "eint", "io_disabled"],
                PK2: ["gpio_in", "gpio_out", "null", "mcsia", "null", "uart7", "spi1", "ncsi", "lbus", "i2s1_lrck", "null", "null", "null", "null", "eint", "io_disabled"],
                PK3: ["gpio_in", "gpio_out", "null", "mcsia", "null", "uart7", "spi1", "ncsi", "lbus", "i2s1_dout0", "null", "null", "null", "null", "eint", "io_disabled"],
                PK4: ["gpio_in", "gpio_out", "null", "mcsia", "null", "twi1", "spi1", "ncsi", "lbus", "i2s1_din0", "null", "null", "null", "null", "eint", "io_disabled"],
                PK5: ["gpio_in", "gpio_out", "null", "mcsia", "null", "twi1", "spi1", "ncsi", "lbus", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK6: ["gpio_in", "gpio_out", "null", "mcsib", "null", "mcsi0", "spi1", "ncsi", "lbus", "uart3", "null", "null", "null", "null", "eint", "io_disabled"],
                PK7: ["gpio_in", "gpio_out", "null", "mcsib", "null", "twi2", "spi1", "ncsi", "lbus", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK8: ["gpio_in", "gpio_out", "null", "mcsib", "null", "twi2", "spi1", "ncsi", "lbus", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK9: ["gpio_in", "gpio_out", "null", "mcsib", "null", "mcsi1", "spi1", "ncsi", "lbus", "uart3", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
        rtc_pio: {
            reg_base: 0x7096000,
            version: 6,
            pin_bank_num: {
                PW: 6
            },
            pin_mux: {
                PW0: ["gpio_in", "gpio_out", "nmi", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PW1: ["gpio_in", "gpio_out", "pwr_irq0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PW2: ["gpio_in", "gpio_out", "pwr_irq1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PW3: ["gpio_in", "gpio_out", "pwr_irq2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PW4: ["gpio_in", "gpio_out", "pwr_irq3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PW5: ["gpio_in", "gpio_out", "pwr_irq4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
    }
};