import type { ChipInfo } from '../Drivers/Types';

export const aw1903: ChipInfo = {
    id: '1903',
    chipMark: {
        "A733MX-NX3": 0x5F00,
        "A733": 0x0
    },
    pinctrl: {
        pio: {
            reg_base: 0x2000000,
            version: 3,
            pin_bank_num: {
                PB: 11,
                PC: 17,
                PD: 24,
                PE: 16,
                PF: 7,
                PG: 15,
                PH: 20,
                PI: 17,
                PJ: 28,
                PK: 26
            },
            pin_mux: {
                PB0: ["gpio_in", "gpio_out", "uart2", "uart0", "spi2", "dsi", "lcd0", "jtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB1: ["gpio_in", "gpio_out", "uart2", "uart0", "spi2", "null", "lcd0", "jtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB10: ["gpio_in", "gpio_out", "uart0", "i2s0_din3", "i2s0_dout3", "pwm1_2", "pll", "lcd0", "twi8", "twi0", "test", "null", "null", "null", "eint", "io_disabled"],
                PB2: ["gpio_in", "gpio_out", "uart2", "null", "spi2", "hdmi", "lcd0", "jtag", "twi0", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB3: ["gpio_in", "gpio_out", "uart2", "null", "spi2", "hdmi", "lcd0", "jtag", "twi0", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB4: ["gpio_in", "gpio_out", "pwm0_0", "i2s0_mclk", "spi2", "hdmi", "lcd0", "trace", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB5: ["gpio_in", "gpio_out", "null", "i2s0_bclk", "spi2", "pwm0_1", "lcd0", "trace", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB6: ["gpio_in", "gpio_out", "clk", "i2s0_lrck", "spi2", "pwm0_2", "pwm0_8", "trace", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB7: ["gpio_in", "gpio_out", "clk", "i2s0_dout0", "i2s0_din1", "pwm0_9", "owa0", "trace", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB8: ["gpio_in", "gpio_out", "clk", "i2s0_din0", "i2s0_dout1", "pwm1_0", "owa0", "trace", "twi1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB9: ["gpio_in", "gpio_out", "uart0", "i2s0_din2", "i2s0_dout2", "pwm1_1", "watchdog", "lcd0", "twi8", "twi0", "test", "null", "null", "null", "eint", "io_disabled"],
                PC0: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC1: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC10: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC11: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC12: ["gpio_in", "gpio_out", "nand", "null", "null", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC13: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC14: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC15: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC16: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC2: ["gpio_in", "gpio_out", "nand", "null", "null", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC3: ["gpio_in", "gpio_out", "nand", "null", "null", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC4: ["gpio_in", "gpio_out", "nand", "null", "null", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC5: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC6: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC7: ["gpio_in", "gpio_out", "nand", "null", "null", "spi0", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC8: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC9: ["gpio_in", "gpio_out", "nand", "sdc2", "sdc3", "null", "spif0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD0: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD1: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD10: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "spi1", "pwm1_0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD11: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "spi1", "pwm1_1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD12: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "spi1", "pwm1_2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD13: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "spi1", "pwm1_3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD14: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "spi1", "uart3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD15: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "spi1", "uart3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD16: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "twi2", "uart3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD17: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "twi2", "uart3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD18: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "spi1", "uart4", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD19: ["gpio_in", "gpio_out", "lcd0", "lvds1", "dsi1", "eink", "pwm1_5", "uart4", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD2: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD20: ["gpio_in", "gpio_out", "lcd0", "dsi", "twi0", "eink", "pcie", "uart4", "twi3", "pwm0_2", "null", "null", "null", "null", "eint", "io_disabled"],
                PD21: ["gpio_in", "gpio_out", "lcd0", "null", "twi0", "eink", "pcie", "uart4", "twi3", "pwm0_3", "null", "null", "null", "null", "eint", "io_disabled"],
                PD22: ["gpio_in", "gpio_out", "pwm0_4", "null", "null", "eink", "pcie", "twi0", "twi2", "pwm1_4", "null", "null", "null", "null", "eint", "io_disabled"],
                PD23: ["gpio_in", "gpio_out", "pwm0_5", "null", "null", "null", "pcie", "twi0", "twi2", "pwm1_5", "null", "null", "null", "null", "eint", "io_disabled"],
                PD3: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD4: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_4", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD5: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_5", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD6: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_6", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD7: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD8: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD9: ["gpio_in", "gpio_out", "lcd0", "lvds0", "dsi0", "eink", "null", "pwm0_9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE0: ["gpio_in", "gpio_out", "mcsi0", "csi0", "null", "spi3", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE1: ["gpio_in", "gpio_out", "twi2", "csi1", "null", "spi3", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE10: ["gpio_in", "gpio_out", "twi4", "tcon", "i2s3_din3", "i2s3_dout3", "lpc", "ncsi0", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE11: ["gpio_in", "gpio_out", "twi4", "spi3", "i2s3_din2", "i2s3_dout2", "pcie", "ncsi0", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE12: ["gpio_in", "gpio_out", "null", "spi3", "i2s3_dout0", "i2s3_din1", "pcie", "null", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE13: ["gpio_in", "gpio_out", "null", "spi3", "null", "null", "pcie", "null", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE14: ["gpio_in", "gpio_out", "null", "spi3", "null", "pwm1_8", "pcie", "ir", "twi9", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE15: ["gpio_in", "gpio_out", "null", "spi3", "null", "pwm1_9", "ir", "null", "twi9", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE2: ["gpio_in", "gpio_out", "twi2", "csi0", "null", "spi3", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE3: ["gpio_in", "gpio_out", "twi3", "csi1", "pwm0_0", "spi3", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE4: ["gpio_in", "gpio_out", "twi3", "ledc", "pwm0_1", "spi3", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE5: ["gpio_in", "gpio_out", "mcsi1", "pll", "null", "pwm0_2", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE6: ["gpio_in", "gpio_out", "clk", "hdmi", "i2s3_din0", "i2s3_dout1", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE7: ["gpio_in", "gpio_out", "clk", "hdmi", "i2s3_bclk", "null", "lpc", "ncsi0", "twi11", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE8: ["gpio_in", "gpio_out", "clk", "hdmi", "i2s3_lrck", "null", "lpc", "ncsi0", "twi11", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE9: ["gpio_in", "gpio_out", "mcsi2", "tcon", "i2s3_mclk", "null", "lpc", "ncsi0", "uart6", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF0: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "uart5", "twi2", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF1: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF2: ["gpio_in", "gpio_out", "sdc0", "uart0", "trace", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF3: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "uart5", "twi2", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF4: ["gpio_in", "gpio_out", "sdc0", "uart0", "null", "uart5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF5: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace", "uart5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF6: ["gpio_in", "gpio_out", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG0: ["gpio_in", "gpio_out", "sdc1", "lcd0", "pwm1_1", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG1: ["gpio_in", "gpio_out", "sdc1", "lcd0", "pwm1_2", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG10: ["gpio_in", "gpio_out", "i2s1_mclk", "clk", "pwm1_9", "lpc", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG11: ["gpio_in", "gpio_out", "i2s1_bclk", "twi12", "twi9", "sgpio", "dmic", "hdmi", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG12: ["gpio_in", "gpio_out", "i2s1_lrck", "twi12", "twi9", "sgpio", "dmic", "hdmi", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG13: ["gpio_in", "gpio_out", "i2s1_dout0", "i2s1_din1", "twi6", "sgpio", "dmic", "hdmi", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG14: ["gpio_in", "gpio_out", "i2s1_din0", "i2s1_dout1", "twi6", "sgpio", "dmic", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG2: ["gpio_in", "gpio_out", "sdc1", "lcd0", "pwm1_3", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG3: ["gpio_in", "gpio_out", "sdc1", "lcd0", "pwm1_4", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG4: ["gpio_in", "gpio_out", "sdc1", "lcd0", "pwm1_5", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG5: ["gpio_in", "gpio_out", "sdc1", "lcd0", "pwm1_6", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG6: ["gpio_in", "gpio_out", "uart1", "uart4", "pwm1_7", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG7: ["gpio_in", "gpio_out", "uart1", "uart4", "pwm1_8", "lpc", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG8: ["gpio_in", "gpio_out", "uart1", "uart4", "uart5", "lpc", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG9: ["gpio_in", "gpio_out", "uart1", "uart4", "uart5", "lpc", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH0: ["gpio_in", "gpio_out", "twi0", "i2s2_dout2", "i2s2_din2", "rgmii0", "twi3", "spi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH1: ["gpio_in", "gpio_out", "twi0", "i2s2_dout3", "i2s2_din3", "rgmii0", "twi3", "spi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH10: ["gpio_in", "gpio_out", "dmic", "spi2", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH11: ["gpio_in", "gpio_out", "dmic", "spi2", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH12: ["gpio_in", "gpio_out", "dmic", "spi2", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH13: ["gpio_in", "gpio_out", "uart5", "null", "null", "rgmii0", "twi7", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH14: ["gpio_in", "gpio_out", "uart5", "null", "null", "rgmii0", "twi7", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH15: ["gpio_in", "gpio_out", "uart5", "ledc", "dsi", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH16: ["gpio_in", "gpio_out", "uart5", "null", "spi2", "ir", "twi5", "twi6", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH17: ["gpio_in", "gpio_out", "null", "null", "spi2", "ir", "twi5", "twi6", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH18: ["gpio_in", "gpio_out", "null", "null", "spi2", "pwm1_8", "null", "twi7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH19: ["gpio_in", "gpio_out", "null", "null", "spi2", "pwm1_9", "null", "twi7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH2: ["gpio_in", "gpio_out", "twi1", "null", "i2s2_mclk", "rgmii0", "null", "spi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH3: ["gpio_in", "gpio_out", "twi1", "null", "i2s2_bclk", "rgmii0", "null", "spi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH4: ["gpio_in", "gpio_out", "uart3", "spi2", "i2s2_lrck", "rgmii0", "null", "spi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH5: ["gpio_in", "gpio_out", "uart3", "i2s2_din1", "i2s2_dout0", "rgmii0", "null", "spi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH6: ["gpio_in", "gpio_out", "uart3", "i2s2_dout1", "i2s2_din0", "rgmii0", "null", "spi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH7: ["gpio_in", "gpio_out", "uart3", "spi2", "dsi", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH8: ["gpio_in", "gpio_out", "dmic", "spi2", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH9: ["gpio_in", "gpio_out", "dmic", "spi2", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI0: ["gpio_in", "gpio_out", "null", "uart4", "null", "pwm0_1", "twi3", "twi4", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI1: ["gpio_in", "gpio_out", "null", "uart4", "null", "pwm0_2", "twi3", "twi4", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI10: ["gpio_in", "gpio_out", "owa0", "null", "pcie", "pwm1_1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI11: ["gpio_in", "gpio_out", "owa0", "uart5", "uart3", "pwm1_2", "twi5", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI12: ["gpio_in", "gpio_out", "ir", "uart5", "uart3", "pwm1_3", "twi5", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI13: ["gpio_in", "gpio_out", "uart2", "uart3", "pcie", "pwm1_4", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI14: ["gpio_in", "gpio_out", "uart2", "uart3", "pcie", "pwm1_5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI15: ["gpio_in", "gpio_out", "uart3", "uart1", "null", "pwm1_6", "twi8", "twi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI16: ["gpio_in", "gpio_out", "uart3", "uart1", "null", "pwm1_7", "twi8", "twi2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI2: ["gpio_in", "gpio_out", "uart6", "null", "spi4", "pwm0_3", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI3: ["gpio_in", "gpio_out", "uart6", "null", "spi4", "pwm0_4", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI4: ["gpio_in", "gpio_out", "uart6", "null", "spi4", "pwm0_5", "twi11", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI5: ["gpio_in", "gpio_out", "uart6", "null", "spi4", "pwm0_6", "twi11", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI6: ["gpio_in", "gpio_out", "uart6", "uart0", "spi4", "pwm0_7", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI7: ["gpio_in", "gpio_out", "uart6", "uart0", "spi4", "pwm0_8", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI8: ["gpio_in", "gpio_out", "uart6", "uart5", "ir", "pwm0_9", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI9: ["gpio_in", "gpio_out", "uart6", "uart5", "spi4", "pwm1_0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ0: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ1: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ10: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ11: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ12: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ13: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ14: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ15: ["gpio_in", "gpio_out", "lcd1", "lvds3", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ16: ["gpio_in", "gpio_out", "lcd1", "lvds3", "uart5", "i2s4_bclk", "null", "twi7", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ17: ["gpio_in", "gpio_out", "lcd1", "lvds3", "uart5", "i2s4_mclk", "null", "twi7", "spi3", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ18: ["gpio_in", "gpio_out", "lcd1", "lvds3", "uart5", "i2s4_lrck", "pwm0_0", "null", "twi4", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ19: ["gpio_in", "gpio_out", "lcd1", "lvds3", "uart5", "i2s4_din0", "i2s4_dout1", "null", "twi4", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ2: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ20: ["gpio_in", "gpio_out", "lcd1", "null", "uart3", "i2s4_dout0", "i2s4_din1", "twi12", "twi10", "lcd0", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ21: ["gpio_in", "gpio_out", "lcd1", "pwm1_3", "uart3", "null", "spi3", "twi12", "twi10", "lcd0", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ22: ["gpio_in", "gpio_out", "lcd1", "pwm1_4", "uart3", "uart2", "twi7", "twi3", "twi11", "lcd0", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ23: ["gpio_in", "gpio_out", "lcd1", "pwm1_5", "uart3", "uart2", "twi7", "twi3", "twi11", "lcd0", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ24: ["gpio_in", "gpio_out", "lcd1", "pwm1_6", "uart4", "null", "null", "twi4", "spi3", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ25: ["gpio_in", "gpio_out", "lcd1", "pwm1_7", "uart4", "null", "null", "twi4", "spi3", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ26: ["gpio_in", "gpio_out", "lcd1", "pwm1_8", "uart4", "uart2", "null", "twi5", "spi3", "lcd0", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ27: ["gpio_in", "gpio_out", "lcd1", "pwm1_9", "uart4", "uart2", "dsi", "twi5", "spi3", "lcd0", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ3: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ4: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ5: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ6: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ7: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ8: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ9: ["gpio_in", "gpio_out", "lcd1", "lvds2", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK0: ["gpio_in", "gpio_out", "mcsia", "uart6", "i2s4_bclk", "hdmi", "twi1", "ncsi1", "sgpio", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK1: ["gpio_in", "gpio_out", "mcsia", "uart6", "i2s4_mclk", "hdmi", "twi1", "ncsi1", "sgpio", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK10: ["gpio_in", "gpio_out", "mcsib", "uart6", "null", "pwm0_3", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK11: ["gpio_in", "gpio_out", "mcsib", "uart6", "null", "pwm0_4", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK12: ["gpio_in", "gpio_out", "mcsib", "uart6", "null", "pwm0_5", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK13: ["gpio_in", "gpio_out", "mcsib", "uart6", "null", "pwm0_6", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK14: ["gpio_in", "gpio_out", "mcsib", "pcie", "null", "pwm0_7", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK15: ["gpio_in", "gpio_out", "mcsib", "null", "null", "pwm0_8", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK16: ["gpio_in", "gpio_out", "mcsib", "twi3", "uart2", "pwm0_9", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK17: ["gpio_in", "gpio_out", "mcsib", "twi3", "uart2", "pwm1_0", "null", "ncsi1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK18: ["gpio_in", "gpio_out", "mcsib", "mcsi1", "uart2", "pwm1_1", "null", "ncsi1", "twi9", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK19: ["gpio_in", "gpio_out", "mcsib", "mcsi2", "uart2", "pwm1_2", "null", "ncsi1", "twi9", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK2: ["gpio_in", "gpio_out", "mcsia", "uart6", "i2s4_lrck", "hdmi", "twi5", "ncsi1", "sgpio", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK20: ["gpio_in", "gpio_out", "mcsic", "twi2", "uart3", "pwm0_1", "null", "ncsi1", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK21: ["gpio_in", "gpio_out", "mcsic", "twi2", "uart3", "pwm0_2", "null", "ncsi1", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK22: ["gpio_in", "gpio_out", "mcsic", "twi3", "uart3", "pwm1_6", "null", "ncsi1", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK23: ["gpio_in", "gpio_out", "mcsic", "twi3", "uart3", "pwm1_7", "null", "ncsi1", "uart1", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK24: ["gpio_in", "gpio_out", "mcsic", "mcsi0", "pwm0_6", "twi12", "null", "null", "twi10", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK25: ["gpio_in", "gpio_out", "mcsic", "mcsi1", "pwm0_7", "twi12", "null", "null", "twi10", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK3: ["gpio_in", "gpio_out", "mcsia", "uart6", "i2s4_din0", "i2s4_dout1", "twi5", "ncsi1", "sgpio", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK4: ["gpio_in", "gpio_out", "mcsia", "pcie", "i2s4_dout0", "i2s4_din1", "spi3", "ncsi1", "jtag", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK5: ["gpio_in", "gpio_out", "mcsia", "pcie", "pwm1_8", "pwm1_9", "spi3", "ncsi1", "jtag", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK6: ["gpio_in", "gpio_out", "mcsia", "twi2", "uart4", "uart2", "spi3", "ncsi1", "jtag", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK7: ["gpio_in", "gpio_out", "mcsia", "twi2", "uart4", "uart2", "spi3", "ncsi1", "jtag", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK8: ["gpio_in", "gpio_out", "mcsia", "mcsi0", "uart4", "uart2", "spi3", "ncsi1", "jtag", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK9: ["gpio_in", "gpio_out", "mcsia", "mcsi2", "uart4", "uart2", "null", "ncsi1", "jtag", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
        rtc_pio: {
            reg_base: 0x7025000,
            version: 5,
            pin_bank_num: {
                PL: 14,
                PM: 6
            },
            pin_mux: {
                PL0: ["gpio_in", "gpio_out", "s_twi0", "s_twi1", "s_twi2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL1: ["gpio_in", "gpio_out", "s_twi0", "s_twi1", "s_twi2", "s_ir_rx", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL10: ["gpio_in", "gpio_out", "s_uart0", "s_twi2", "s_uart1", "null", "s_pwm0_8", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL11: ["gpio_in", "gpio_out", "s_uart0", "s_twi2", "s_uart1", "s_ir_rx", "s_pwm0_9", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL12: ["gpio_in", "gpio_out", "s_uart1", "s_twi1", "s_twi2", "s_ir_rx", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL13: ["gpio_in", "gpio_out", "s_uart1", "s_twi1", "s_twi2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL2: ["gpio_in", "gpio_out", "s_uart1", "s_uart0", "s_twi1", "null", "s_pwm0_0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL3: ["gpio_in", "gpio_out", "s_uart1", "s_uart0", "s_twi1", "s_ir_rx", "s_pwm0_1", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL4: ["gpio_in", "gpio_out", "s_jtag_ms", "s_twi2", "s_spi0", "s_ir_rx", "s_pwm0_2", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL5: ["gpio_in", "gpio_out", "s_jtag_ck", "s_twi2", "s_spi0", "null", "s_pwm0_3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL6: ["gpio_in", "gpio_out", "s_jtag_do", "s_uart0", "s_spi0", "s_ir_rx", "s_pwm0_4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL7: ["gpio_in", "gpio_out", "s_jtag_di", "s_uart0", "s_spi0", "null", "s_pwm0_5", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL8: ["gpio_in", "gpio_out", "s_twi1", "s_uart1", "s_twi0", "s_twi2", "s_pwm0_6", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL9: ["gpio_in", "gpio_out", "s_twi1", "s_uart1", "s_twi0", "s_twi2", "s_pwm0_7", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM0: ["gpio_in", "gpio_out", "s_jtag_ms", "s_spi0", "s_rjtag_ms", "s_twi1", "s_pwm0_2", "s_ir_rx", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM1: ["gpio_in", "gpio_out", "s_jtag_ck", "s_spi0", "s_rjtag_ck", "s_twi1", "s_pwm0_3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM2: ["gpio_in", "gpio_out", "s_jtag_do", "s_spi0", "s_uart0", "s_uart1", "s_pwm0_4", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM3: ["gpio_in", "gpio_out", "s_jtag_di", "s_spi0", "s_uart0", "s_uart1", "s_pwm0_5", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM4: ["gpio_in", "gpio_out", "s_uart0", "s_twi2", "s_twi1", "s_uart1", "s_pwm0_0", "s_ir_rx", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM5: ["gpio_in", "gpio_out", "s_uart0", "s_twi2", "s_twi1", "s_uart1", "s_pwm0_1", "s_ir_rx", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
    }
};