import type { ChipInfo } from '../Drivers/Types';

export const aw1912: ChipInfo = {
    id: '1912',
    chipMark: {
        "T536": 0x0,
        "MR536": 0x0
    },
    pinctrl: {
        pio: {
            reg_base: 0x3604000,
            version: 3,
            pin_bank_num: {
                PA: 10,
                PB: 15,
                PC: 17,
                PD: 24,
                PE: 18,
                PF: 7,
                PG: 15,
                PH: 16,
                PI: 17,
                PJ: 32,
                PK: 24
            },
            pin_mux: {
                PA0: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA1: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA2: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA3: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA4: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA5: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA6: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA7: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA8: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PA9: ["gpio_in", "gpio_out", "gpadc0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB0: ["gpio_in", "gpio_out", "uart2", "spi4", "jtag", "pwm0_6", "test", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB1: ["gpio_in", "gpio_out", "uart2", "spi4", "jtag", "pwm0_7", "test", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB10: ["gpio_in", "gpio_out", "uart0", "i2s2_din3", "pwm0_1", "i2s2_dout3", "twi0", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB11: ["gpio_in", "gpio_out", "twi5", "uart7", "spi1", "pwm0_2", "watchdog_sig", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB12: ["gpio_in", "gpio_out", "twi5", "uart7", "spi1", "pwm0_3", "pll_lock_dbg", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB13: ["gpio_in", "gpio_out", "twi4", "uart7", "spi1", "pwm0_4", "ir_rx2", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB14: ["gpio_in", "gpio_out", "twi4", "uart7", "spi1", "pwm0_5", "ir_rx3", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB2: ["gpio_in", "gpio_out", "uart2", "spi4", "jtag", "null", "null", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB3: ["gpio_in", "gpio_out", "uart2", "spi4", "jtag", "null", "null", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB4: ["gpio_in", "gpio_out", "twi1", "i2s2_mclk", "trace_data2", "pwm0_8", "ir_rx0", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB5: ["gpio_in", "gpio_out", "twi1", "i2s2_bclk", "trace_clk", "pwm0_9", "ir_rx1", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB6: ["gpio_in", "gpio_out", "null", "i2s2_lrck", "trace_data0", "pwm1_0", "ir_tx", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB7: ["gpio_in", "gpio_out", "owa_in", "i2s2_dout0", "i2s2_din1", "pwm1_1", "null", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB8: ["gpio_in", "gpio_out", "owa_out", "i2s2_din0", "i2s2_dout1", "pwm0_0", "null", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PB9: ["gpio_in", "gpio_out", "uart0", "i2s2_din2", "trace_data1", "i2s2_dout2", "twi0", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC0: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC1: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC10: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC11: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC12: ["gpio_in", "gpio_out", "nand", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC13: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC14: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC15: ["gpio_in", "gpio_out", "nand", "sdc2", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC16: ["gpio_in", "gpio_out", "nand", "sdc2", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC2: ["gpio_in", "gpio_out", "nand", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC3: ["gpio_in", "gpio_out", "nand", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC4: ["gpio_in", "gpio_out", "nand", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC5: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC6: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC7: ["gpio_in", "gpio_out", "nand", "null", "spi0", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC8: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PC9: ["gpio_in", "gpio_out", "nand", "sdc2", "null", "spif", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD0: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_0", "null", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD1: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_1", "null", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD10: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_0", "twi6", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD11: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_1", "twi6", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD12: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_2", "null", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD13: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_3", "null", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD14: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_4", "uart3", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD15: ["gpio_in", "gpio_out", "lcd", "lvds1", "spi1", "pwm1_5", "uart3", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD16: ["gpio_in", "gpio_out", "lcd", "lvds1", "null", "pwm1_6", "uart3", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD17: ["gpio_in", "gpio_out", "lcd", "lvds1", "null", "pwm1_7", "uart3", "uart8", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD18: ["gpio_in", "gpio_out", "lcd", "lvds1", "twi6", "pwm1_8", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD19: ["gpio_in", "gpio_out", "lcd", "lvds1", "twi6", "pwm1_9", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD2: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_2", "null", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD20: ["gpio_in", "gpio_out", "lcd", "pwm0_2", "uart2", "twi5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD21: ["gpio_in", "gpio_out", "lcd", "pwm0_3", "uart2", "twi5", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD22: ["gpio_in", "gpio_out", "null", "pwm0_1", "uart2", "twi4", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD23: ["gpio_in", "gpio_out", "null", "pwm0_0", "uart2", "twi4", "twi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD3: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_3", "null", "uart9", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD4: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_4", "null", "uart10", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD5: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_5", "null", "uart10", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD6: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_6", "null", "uart10", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD7: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_7", "null", "uart10", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD8: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_8", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PD9: ["gpio_in", "gpio_out", "lcd", "lvds0", "dsi", "pwm0_9", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE0: ["gpio_in", "gpio_out", "mcsi0_mclk", "null", "null", "null", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE1: ["gpio_in", "gpio_out", "twi2", "uart4", "null", "null", "spi3", "lbus_cs1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE10: ["gpio_in", "gpio_out", "mcsi3_mclk", "pwm0_3", "ncsi_d2", "null", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE11: ["gpio_in", "gpio_out", "twi1", "uart5", "ncsi_d3", "uart6", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE12: ["gpio_in", "gpio_out", "twi1", "uart5", "ncsi_d4", "uart6", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE13: ["gpio_in", "gpio_out", "twi4", "uart5", "ncsi_d5", "uart6", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE14: ["gpio_in", "gpio_out", "twi4", "uart5", "ncsi_d6", "uart6", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE15: ["gpio_in", "gpio_out", "mcsi2_mclk", "pwm0_2", "ncsi_d7", "null", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE16: ["gpio_in", "gpio_out", "twi6", "pwm0_4", "csi0_xvs_fsync", "twi0", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE17: ["gpio_in", "gpio_out", "twi6", "pwm0_5", "csi1_xvs_fsync", "twi0", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE2: ["gpio_in", "gpio_out", "twi2", "uart4", "null", "null", "spi3", "lbus_cs2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE3: ["gpio_in", "gpio_out", "twi3", "uart4", "csi0_xhs", "null", "spi3", "lbus_cs3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE4: ["gpio_in", "gpio_out", "twi3", "uart4", "csi1_xhs", "null", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE5: ["gpio_in", "gpio_out", "mcsi1_mclk", "pll_lock_dbg", "null", "ledc", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE6: ["gpio_in", "gpio_out", "null", "uart12", "twi2", "tcon_fsync0<tcon_lcd0>", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE7: ["gpio_in", "gpio_out", "null", "uart12", "twi2", "clk_fanout0", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE8: ["gpio_in", "gpio_out", "null", "uart12", "ncsi_d0", "clk_fanout1", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PE9: ["gpio_in", "gpio_out", "null", "uart12", "ncsi_d1", "null", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF0: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace_data2", "i2s3_din0", "i2s3_dout1", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF1: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace_data1", "i2s3_dout0", "i2s3_din1", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF2: ["gpio_in", "gpio_out", "sdc0", "uart0", "null", "i2s3_din2", "spi4", "i2s3_dout2", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF3: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace_data0", "i2s3_lrck", "spi4", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF4: ["gpio_in", "gpio_out", "sdc0", "uart0", "null", "i2s3_din3", "spi4", "i2s3_dout3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF5: ["gpio_in", "gpio_out", "sdc0", "jtag", "trace_clk", "i2s3_bclk", "spi4", "rjtag", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PF6: ["gpio_in", "gpio_out", "null", "null", "null", "i2s3_mclk", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG0: ["gpio_in", "gpio_out", "sdc1", "null", "uart13", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG1: ["gpio_in", "gpio_out", "sdc1", "null", "uart13", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG10: ["gpio_in", "gpio_out", "uart14", "i2s1_mclk", "twi2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG11: ["gpio_in", "gpio_out", "uart14", "i2s1_bclk", "twi2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG12: ["gpio_in", "gpio_out", "uart14", "i2s1_lrck", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG13: ["gpio_in", "gpio_out", "uart14", "i2s1_dout0", "i2s1_din1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG14: ["gpio_in", "gpio_out", "null", "i2s1_din0", "i2s1_dout1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG2: ["gpio_in", "gpio_out", "sdc1", "pcie_perstn", "uart13", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG3: ["gpio_in", "gpio_out", "sdc1", "pcie_waken", "uart13", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG4: ["gpio_in", "gpio_out", "sdc1", "pcie_clkreqn", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG5: ["gpio_in", "gpio_out", "sdc1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG6: ["gpio_in", "gpio_out", "uart1", "twi6", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG7: ["gpio_in", "gpio_out", "uart1", "twi6", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG8: ["gpio_in", "gpio_out", "uart1", "twi5", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PG9: ["gpio_in", "gpio_out", "uart1", "twi5", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH0: ["gpio_in", "gpio_out", "twi0", "pwm2_4", "uart1", "null", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH1: ["gpio_in", "gpio_out", "twi0", "pwm2_5", "uart1", "null", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH10: ["gpio_in", "gpio_out", "pwm2_8", "null", "i2s3_bclk", "lcd", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH11: ["gpio_in", "gpio_out", "ir_rx3", "pwm2_9", "i2s3_lrck", "lcd", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH12: ["gpio_in", "gpio_out", "ir_rx1", "i2s3_dout0", "i2s3_din1", "lcd", "null", "uart11", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH13: ["gpio_in", "gpio_out", "ir_rx2", "i2s3_dout1", "i2s3_din0", "lcd", "null", "uart11", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH14: ["gpio_in", "gpio_out", "ir_tx", "i2s3_dout2", "i2s3_din2", "pwm1_5", "null", "uart11", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH15: ["gpio_in", "gpio_out", "ir_rx0", "i2s3_dout3", "i2s3_din3", "ledc", "null", "uart11", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH2: ["gpio_in", "gpio_out", "twi1", "cpu_cur_w", "uart1", "clk_fanout0", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH3: ["gpio_in", "gpio_out", "twi1", "ir_tx", "uart1", "clk_fanout1", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH4: ["gpio_in", "gpio_out", "uart3", "spi3", "cpu_cur_w", "pwm1_4", "dmic", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH5: ["gpio_in", "gpio_out", "uart3", "spi3", "ledc", "pcie_perstn", "dmic", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH6: ["gpio_in", "gpio_out", "uart3", "spi3", "twi6", "pcie_waken", "dmic", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH7: ["gpio_in", "gpio_out", "uart3", "spi3", "twi6", "pcie_clkreqn", "dmic", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH8: ["gpio_in", "gpio_out", "pwm2_6", "spi3", "owa_in", "lcd", "dmic", "twi3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PH9: ["gpio_in", "gpio_out", "pwm2_7", "spi3", "i2s3_mclk", "lcd", "null", "twi3", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI0: ["gpio_in", "gpio_out", "i2s0_bclk", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI1: ["gpio_in", "gpio_out", "i2s0_lrck", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI10: ["gpio_in", "gpio_out", "owa_out", "spi2", "pwm2_7", "i2s0_dout0", "i2s0_din1", "pcie_perstn", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI11: ["gpio_in", "gpio_out", "twi3", "spi2", "pwm2_8", "i2s0_din0", "i2s0_dout1", "pcie_waken", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI12: ["gpio_in", "gpio_out", "twi3", "pwm2_4", "dmic", "i2s0_din3", "i2s0_dout3", "pcie_clkreqn", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI13: ["gpio_in", "gpio_out", "uart4", "pwm2_5", "dmic", "null", "ir_rx0", "i2s3_bclk", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI14: ["gpio_in", "gpio_out", "uart4", "pwm2_6", "dmic", "null", "ir_rx1", "i2s3_lrck", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI15: ["gpio_in", "gpio_out", "uart4", "twi2", "dmic", "null", "ir_rx2", "i2s3_din0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI16: ["gpio_in", "gpio_out", "uart4", "twi2", "dmic", "null", "ir_rx3", "i2s3_mclk", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI2: ["gpio_in", "gpio_out", "i2s0_din0", "uart9", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI3: ["gpio_in", "gpio_out", "i2s0_mclk", "uart9", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI4: ["gpio_in", "gpio_out", "twi5", "uart9", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI5: ["gpio_in", "gpio_out", "twi5", "uart9", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI6: ["gpio_in", "gpio_out", "uart6", "spi2", "pwm2_0", "i2s0_mclk", "ledc", "clk_fanout0", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI7: ["gpio_in", "gpio_out", "uart6", "spi2", "pwm2_1", "i2s0_din2", "i2s0_dout2", "clk_fanout1", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI8: ["gpio_in", "gpio_out", "uart6", "spi2", "pwm2_2", "i2s0_bclk", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PI9: ["gpio_in", "gpio_out", "uart6", "spi2", "pwm2_3", "i2s0_lrck", "null", "ir_tx", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ0: ["gpio_in", "gpio_out", "pwm0_0", "i2s2_mclk", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ1: ["gpio_in", "gpio_out", "pwm0_1", "i2s2_bclk", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ10: ["gpio_in", "gpio_out", "pwm2_0", "i2s1_dout0", "i2s1_din1", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ11: ["gpio_in", "gpio_out", "pwm2_1", "i2s1_din0", "i2s1_dout1", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ12: ["gpio_in", "gpio_out", "pwm2_2", "uart10", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ13: ["gpio_in", "gpio_out", "pwm2_3", "uart10", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ14: ["gpio_in", "gpio_out", "pwm2_4", "uart10", "twi6", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ15: ["gpio_in", "gpio_out", "pwm2_5", "uart10", "twi6", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ16: ["gpio_in", "gpio_out", "pwm2_6", "null", "ir_rx0", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ17: ["gpio_in", "gpio_out", "pwm2_7", "null", "ir_rx1", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ18: ["gpio_in", "gpio_out", "pwm2_8", "null", "ir_rx2", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ19: ["gpio_in", "gpio_out", "pwm2_9", "null", "ir_rx3", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ2: ["gpio_in", "gpio_out", "pwm0_2", "i2s2_lrck", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ20: ["gpio_in", "gpio_out", "twi0", "uart14", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ21: ["gpio_in", "gpio_out", "twi0", "uart14", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ22: ["gpio_in", "gpio_out", "null", "uart14", "ir_tx", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ23: ["gpio_in", "gpio_out", "null", "uart14", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ24: ["gpio_in", "gpio_out", "pwm2_0", "twi4", "uart13", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ25: ["gpio_in", "gpio_out", "pwm2_1", "twi4", "uart13", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ26: ["gpio_in", "gpio_out", "pwm2_2", "twi5", "uart13", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ27: ["gpio_in", "gpio_out", "pwm2_3", "twi5", "uart13", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ28: ["gpio_in", "gpio_out", "null", "twi1", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ29: ["gpio_in", "gpio_out", "null", "twi1", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ3: ["gpio_in", "gpio_out", "pwm0_3", "i2s2_dout0", "i2s2_din1", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ30: ["gpio_in", "gpio_out", "null", "null", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ31: ["gpio_in", "gpio_out", "null", "null", "null", "rgmii1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ4: ["gpio_in", "gpio_out", "pwm0_4", "i2s2_din0", "i2s2_dout1", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ5: ["gpio_in", "gpio_out", "pwm0_5", "i2s2_din2", "i2s2_dout2", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ6: ["gpio_in", "gpio_out", "pwm0_6", "i2s2_din3", "i2s2_dout3", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ7: ["gpio_in", "gpio_out", "pwm0_7", "i2s1_mclk", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ8: ["gpio_in", "gpio_out", "pwm0_8", "i2s1_bclk", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PJ9: ["gpio_in", "gpio_out", "pwm0_9", "i2s1_lrck", "null", "rgmii0", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK0: ["gpio_in", "gpio_out", "mcsia", "null", "uart11", "null", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK1: ["gpio_in", "gpio_out", "mcsia", "null", "uart11", "null", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK10: ["gpio_in", "gpio_out", "mcsib", "twi1", "null", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK11: ["gpio_in", "gpio_out", "mcsib", "twi1", "null", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK12: ["gpio_in", "gpio_out", "mcsic", "uart7", "twi1", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK13: ["gpio_in", "gpio_out", "mcsic", "uart7", "twi1", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK14: ["gpio_in", "gpio_out", "mcsic", "uart7", "uart5", "ncsi", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK15: ["gpio_in", "gpio_out", "mcsic", "uart7", "uart5", "ncsi", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK16: ["gpio_in", "gpio_out", "mcsic", "twi4", "uart5", "ncsi", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK17: ["gpio_in", "gpio_out", "mcsic", "twi4", "uart5", "ncsi", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK18: ["gpio_in", "gpio_out", "mcsid", "mcsi0_mclk", "uart6", "ncsi", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK19: ["gpio_in", "gpio_out", "mcsid", "twi2", "uart6", "ncsi", "spi3", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK2: ["gpio_in", "gpio_out", "mcsia", "twi2", "uart11", "null", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK20: ["gpio_in", "gpio_out", "mcsid", "twi2", "uart6", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK21: ["gpio_in", "gpio_out", "mcsid", "mcsi1_mclk", "uart6", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK22: ["gpio_in", "gpio_out", "mcsid", "twi3", "pwm0_6", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK23: ["gpio_in", "gpio_out", "mcsid", "twi3", "pwm0_7", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK3: ["gpio_in", "gpio_out", "mcsia", "twi2", "uart11", "null", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK4: ["gpio_in", "gpio_out", "mcsia", "null", "uart12", "ncsi", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK5: ["gpio_in", "gpio_out", "mcsia", "null", "uart12", "ncsi", "spi2", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK6: ["gpio_in", "gpio_out", "mcsib", "null", "uart12", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK7: ["gpio_in", "gpio_out", "mcsib", "null", "uart12", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK8: ["gpio_in", "gpio_out", "mcsib", "null", "null", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PK9: ["gpio_in", "gpio_out", "mcsib", "mcsi3_mclk", "null", "ncsi", "null", "lbus", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
        rtc_pio: {
            reg_base: 0x7096000,
            version: 5,
            pin_bank_num: {
                PL: 14,
                PM: 6
            },
            pin_mux: {
                PL0: ["gpio_in", "gpio_out", "s_twi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL1: ["gpio_in", "gpio_out", "s_twi0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL10: ["gpio_in", "gpio_out", "s_pwm0_0", "s_uart0", "null", "null", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL11: ["gpio_in", "gpio_out", "s_ir_rx", "s_uart0", "null", "null", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL12: ["gpio_in", "gpio_out", "s_pwm0_1", "s_uart0", "null", "null", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL13: ["gpio_in", "gpio_out", "s_pwm0_3", "s_uart0", "null", "null", "s_spi0", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL2: ["gpio_in", "gpio_out", "s_uart0", "s_ir_rx", "s_pwm0_2", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL3: ["gpio_in", "gpio_out", "s_uart0", "null", "s_pwm0_3", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL4: ["gpio_in", "gpio_out", "s_jtag_ms", "s_uart1", "s_ir_rx", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL5: ["gpio_in", "gpio_out", "s_jtag_ck", "s_uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL6: ["gpio_in", "gpio_out", "s_jtag_do", "s_uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL7: ["gpio_in", "gpio_out", "s_jtag_di", "s_uart1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL8: ["gpio_in", "gpio_out", "s_twi1", "null", "s_rjtag_ms", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PL9: ["gpio_in", "gpio_out", "s_twi1", "null", "s_rjtag_ck", "s_pwm0_1", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM0: ["gpio_in", "gpio_out", "s_twi0", "s_uart1", "s_pwm0_0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM1: ["gpio_in", "gpio_out", "s_twi0", "s_uart1", "s_pwm0_1", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM2: ["gpio_in", "gpio_out", "s_twi1", "s_uart1", "s_uart0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM3: ["gpio_in", "gpio_out", "s_twi1", "s_uart1", "s_uart0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM4: ["gpio_in", "gpio_out", "null", "s_pwm0_2", "s_uart0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"],
                PM5: ["gpio_in", "gpio_out", "s_ir_rx", "s_pwm0_3", "s_uart0", "null", "null", "null", "null", "null", "null", "null", "null", "null", "eint", "io_disabled"]
            },
        },
    }
};