import { EFEX_ERROR_CODES, isEfexError, EfexError } from '../Library/libEFEX';
import i18n from '../i18n';

/**
 * Represents a solution/action for handling an error.
 *
 * ErrorSolutions provide user-friendly error messages and
 * appropriate popup types for displaying to the user.
 */
export interface ErrorSolution {
  /** Popup title displayed to user */
  title: string;
  /** Detailed error message for user */
  message: string;
  /** Popup type determining visual style and behavior */
  type: 'error' | 'warning' | 'info';
}

/**
 * Custom error type constants for application-specific errors.
 *
 * These errors are not part of EFEX error codes but are
 * generated by the application during specific failure scenarios.
 */
export const CUSTOM_ERRORS = {
  /** Device failed to reconnect after FEL mode transition */
  RECONNECT_FAILED: 'RECONNECT_FAILED',
} as const;

/**
 * Type union of custom error type constants.
 */
export type CustomErrorType = (typeof CUSTOM_ERRORS)[keyof typeof CUSTOM_ERRORS];

/**
 * Gets the solution for a custom application error.
 *
 * @param errorType - Custom error type constant
 * @returns ErrorSolution with title, message, and type
 */
export function getCustomErrorSolution(errorType: CustomErrorType): ErrorSolution {
  switch (errorType) {
    case CUSTOM_ERRORS.RECONNECT_FAILED:
      return {
        type: 'error',
        title: i18n.t('flashManager.felHandler.reconnectFailed'),
        message: i18n.t('flashManager.felHandler.reconnectFailedDetails'),
      };
    default:
      return {
        type: 'error',
        title: i18n.t('errorHandler.unknownError.title'),
        message: i18n.t('errorHandler.unknownError.message'),
      };
  }
}

/**
 * Gets the user-friendly solution for an EFEX error.
 *
 * Maps EFEX error codes to localized error messages and
 * appropriate popup types. Returns null for unknown errors.
 *
 * @param error - Error object to get solution for
 * @returns ErrorSolution or null if no solution available
 */
export function getErrorSolution(error: unknown): ErrorSolution | null {
  if (!isEfexError(error)) {
    return null;
  }

  const efexError = error as EfexError;

  switch (efexError.code) {
    case EFEX_ERROR_CODES.USB_INIT:
      return {
        type: 'error',
        title: i18n.t('errorHandler.usbInit.title'),
        message: i18n.t('errorHandler.usbInit.message'),
      };

    case EFEX_ERROR_CODES.USB_DEVICE_NOT_FOUND:
      return {
        type: 'warning',
        title: i18n.t('errorHandler.deviceNotFound.title'),
        message: i18n.t('errorHandler.deviceNotFound.message'),
      };

    case EFEX_ERROR_CODES.USB_OPEN:
      return {
        type: 'error',
        title: i18n.t('errorHandler.usbOpen.title'),
        message: i18n.t('errorHandler.usbOpen.message'),
      };

    case EFEX_ERROR_CODES.USB_TRANSFER:
      return {
        type: 'error',
        title: i18n.t('errorHandler.usbTransfer.title'),
        message: i18n.t('errorHandler.usbTransfer.message'),
      };

    case EFEX_ERROR_CODES.USB_TIMEOUT:
      return {
        type: 'warning',
        title: i18n.t('errorHandler.usbTimeout.title'),
        message: i18n.t('errorHandler.usbTimeout.message'),
      };

    case EFEX_ERROR_CODES.DEVICE_BUSY:
      return {
        type: 'warning',
        title: i18n.t('errorHandler.deviceBusy.title'),
        message: i18n.t('errorHandler.deviceBusy.message'),
      };

    case EFEX_ERROR_CODES.DEVICE_NOT_READY:
      return {
        type: 'warning',
        title: i18n.t('errorHandler.deviceNotReady.title'),
        message: i18n.t('errorHandler.deviceNotReady.message'),
      };

    case EFEX_ERROR_CODES.INVALID_DEVICE_MODE:
      return {
        type: 'warning',
        title: i18n.t('errorHandler.invalidDeviceMode.title'),
        message: i18n.t('errorHandler.invalidDeviceMode.message'),
      };

    case EFEX_ERROR_CODES.TIMEOUT:
      return {
        type: 'error',
        title: i18n.t('errorHandler.timeout.title'),
        message: i18n.t('errorHandler.timeout.message'),
      };

    case EFEX_ERROR_CODES.PROTOCOL:
      return {
        type: 'error',
        title: i18n.t('errorHandler.protocol.title', 'Protocol Error'),
        message: i18n.t(
          'errorHandler.protocol.message',
          'Device communication lost. The device may have been disconnected.'
        ),
      };
    default:
      // Handle generic USB errors that don't have specific codes
      if (efexError.isUsbError()) {
        return {
          type: 'error',
          title: i18n.t('errorHandler.usbError.title'),
          message: i18n.t('errorHandler.usbError.message', { error: efexError.message }),
        };
      }

      return null;
  }
}

/**
 * Formats an error for log display.
 *
 * Converts various error types to a human-readable string
 * suitable for logging. Handles EfexError, Error instances,
 * and objects with message properties.
 *
 * @param error - Error object of unknown type
 * @returns Formatted error message string
 */
export function formatErrorForLog(error: unknown): string {
  if (isEfexError(error)) {
    const efexError = error as EfexError;
    return `${efexError.name}: ${efexError.message}`;
  }

  if (error instanceof Error) {
    return error.message;
  }

  // Handle objects with message property (e.g., IpcError)
  if (error && typeof error === 'object' && 'message' in error) {
    const message = (error as { message: unknown }).message;
    if (typeof message === 'string') {
      return message;
    }
  }

  return String(error);
}